### ISSUE TITLE
Errors Analyzing Yank Results

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#1032]
I was trying to analyze Yank results. Unfortunately, running the terminal command 

`yank analyze --store=experiments `

on the attached simulation is triggering the following error:

  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 404, in __get__
    value = instance._cache[self.name]
KeyError: 'mbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 404, in __get__
    value = instance._cache[self.name]
KeyError: 'unbiased_decorrelated_u_ln'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/bin/yank", line 11, in <module>
    load_entry_point('yank==0.22.3', 'console_scripts', 'yank')()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/commands/analyze.py", line 108, in dispatch
    analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/analyze.py", line 229, in analyze_directory
    data[phase_name] = phase.analyze_phase()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/analyze.py", line 142, in analyze_phase
    Deltaf_ij, dDeltaf_ij = self.get_free_energy()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 1887, in get_free_energy
    self._compute_free_energy()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 1840, in _compute_free_energy
    nstates = self.mbar.N_k.size
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 406, in __get__
    value = self._get_default(instance)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 427, in _get_default
    value = self._default(self, instance)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 2062, in mbar
    return instance._create_mbar(instance._unbiased_decorrelated_u_ln,
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 406, in __get__
    value = self._get_default(instance)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 427, in _get_default
    value = self._default(self, instance)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 2042, in _unbiased_decorrelated_u_ln
    return instance._compute_mbar_unbiased_energies()[0]
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 1513, in _compute_mbar_unbiased_energies
    restraint_data = self._get_radially_symmetric_restraint_data()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 1319, in _get_radially_symmetric_restraint_data
    end_states = self._get_end_thermodynamic_states()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistateanalyzer.py", line 657, in _get_end_thermodynamic_states
    self._end_thermodynamic_states = self._reporter.read_end_thermodynamic_states()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistatereporter.py", line 438, in read_end_thermodynamic_states
    serialized_standard_system = states_serializations[standard_system_name]
KeyError: 'thermodynamic_states/0'

The simulations is just 10 Yank iterations but  I have the same problem with 1000 Yank iterations. I tested Yank 0.23.0 and 0.22.3 and both have the same problem. In addition, in Yank 0.23.0, I tried to use the new yank.analyze API with the same error. Please let me know if you need more info.

Thanks,
Gaetano

https://drive.google.com/open?id=1NS02PLQzyCOo6wizysZZq9JXLuXVhK8y

**Comment by Lnaden** [comment]
Off the top of my head, that sounds like either trying to resume from a much older file, or the file is corrupted somehow on init. I'll look into that from the drive link you provided.

**Comment by Lnaden** [comment]
Neither of those scenarios seem likely, which is why i am a bit confused and delving into it.

**Comment by nividic** [comment]
@Lnaden I was running Yank from and openeye floe and also using restarting. To make things easier I decide to run Yank without floe and without restarting anything just 10 iterations. I have attached the link to the new Yank file simulation. Also in this case I have the same error (I wanted to exclude that the problem was created by the openeye floe engine or restarting)

This is the new link:

https://drive.google.com/open?id=19w8NwcP_Hw3zDgWDQvW2V_pZBfVxLCYX

Thanks a lot for your help
