### ISSUE TITLE
doubt in yank resum simulation

### ISSUE THREAD

**Issue by biologyfinders** [choderalab/yank#1039]
I have another doubt that is: see if we run yank script first time on the serial mode it will run, but if its stop and I want to run it again then giving following error by making the change in "p-xylene-explicit.yaml" script in the following way:
options:
  minimize: yes
  verbose: yes
  number_of_iterations: 500
  resume_simulation: yes

is this is the correct file to make changes or file should be different, I have made changes as explained in your tutorial(http://getyank.org/0.23.1/yamlpages/options.html?highlight=resume_setup#yaml-options-experiments-dir)after stopping it if I trying to run the script again getting following error:

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Traceback (most recent call last):
  File "/home/naveen/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/commands/script.py", line 110, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 580, in __init__
    self.parse(script)
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 679, in parse
    self._options['precision'])
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 1722, in _configure_platform
    platform = openmm.Platform.getPlatformByName(platform_name)
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 12138, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"
[naveen@localhost t4-lysozyme]$ export OPENMM_CUDA_COMPILER=/usr/local/cuda/bin/nvcc
[naveen@localhost t4-lysozyme]$ export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
[naveen@localhost t4-lysozyme]$ yank script --yaml=p-xylene-explicit.yaml
2018-07-17 16:35:20,249: Setting CUDA platform to use precision model 'mixed'.
2018-07-17 16:35:20,252: Single node: executing <function ExperimentBuilder._check_resume at 0x7fc6fb942378>
2018-07-17 16:35:20,252: ERROR - yank.experiment - system setup directory p-xylene-explicit-output/setup/systems/t4-xylene already exists; cowardly refusing to proceed. Move/delete directory or set resume_setup options
Traceback (most recent call last):
  File "/home/naveen/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 715, in run_experiments
    self._check_resume()
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/mpi.py", line 250, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/mpi.py", line 199, in run_single_node
    result = task(*args, **kwargs)
  File "/home/naveen/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 1641, in _check_resume
    raise YamlParseError(err_msg)
yank.experiment.YamlParseError: system setup directory p-xylene-explicit-output/setup/systems/t4-xylene already exists; cowardly refusing to proceed. Move/delete directory or set resume_setup options
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by jchodera** [comment]
Thanks for posting this!

We've tried to make the error message as informative as possible:
```
yank.experiment.YamlParseError: system setup directory p-xylene-explicit-output/setup/systems/t4-xylene already exists; cowardly refusing to proceed. Move/delete directory or set resume_setup options
```
You will either need to move or delete your setup directory (`p-xylene-explicit-output/setup/systems/t4-xylene`) or change the `resume_setup` option in the YAML file to `yes`.

@Lnaden : Can we change the default behavior to `yes` and update `yank-examples` to resume by default? I've seen this issue a few times.

**Comment by Lnaden** [comment]
Thanks for posting here. 

It looks like you need to set the `resume_setup: yes` flag. You will also want to change the `number_of_iterations` to `default_number_of_iterations` due to a change in the YANK 0.21.0 release. The file I think you are using a is a bit out of date and I will be working on a fix today.

**Comment by Lnaden** [comment]
@jchodera yes, as part of this I am going to update the last example yamls and make a proper cookbook in response to some other things as well.

**Comment by biologyfinders** [comment]
I have added this option:resume_simulation: yes  instead of resume_setup:yes  can u please tell in which file i need to change  i m using this file"p-xylene-explicit.yaml" . please specify.

Thanks

**Comment by andrrizzi** [comment]
Hi @biologyfinders. You need both in the YAML file (`resume_simulation: yes` and `resume_setup: yes`). They are there to avoid overwriting the simulation or the setup files respectively.

**Comment by biologyfinders** [comment]
ok, so that was I mistaking, so i have to add yes for both resume_simulation: yes and resume_setup:  in yank script,  this apply for all 5 energy calculation binding and hydration??

**Comment by andrrizzi** [comment]
Correct.
