### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by dtmoustakas** [choderalab/yank#1052]
Hi,

I'm experiencing a segfault when running YANK.  I get the following error in the stdout:

 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
2018-07-26 11:35:05,884: Node 1/1: waiting for broadcast of <function SAMSSampler._mix_replicas at 0x7fe11b45f2f0>
2018-07-26 11:35:05,885: Propagating all replicas...
2018-07-26 11:35:05,885: Node 1/1: execute _propagate_replica(0)
2018-07-26 11:35:06,412: Node 1/1: sending results of _propagate_replica to 0
2018-07-26 11:35:06,413: Node 1/1: execute _get_replica_move_statistics(0)
2018-07-26 11:35:06,413: Node 1/1: allgather results of _get_replica_move_statistics
2018-07-26 11:35:06,413: Propagating all replicas took    2.993s
2018-07-26 11:35:06,414: Node 1/1: execute _compute_replica_energies(0)

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 28182 RUNNING AT schrogpu1
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

I'm running on an ubuntu 16.04.3 system, with 4 NVIDIA K40s.  The job is managed through MPI, and was running in tmux.  My NVIDIA driver version is 384.98, and I'm using CUDA 9.  I've also run this using OpenCL, and get the same error.

I've attached the YAML file as txt, but am stumped.  I can't find any errors in the log files for the individual experiments, so I don't know how to dig further into this bug.

Thanks for your help!
[sams-twostage-boresch-dense.txt](https://github.com/choderalab/yank/files/2233495/sams-twostage-boresch-dense.txt)

**Comment by jchodera** [comment]
This is probably something going wrong in the C++ layer of OpenMM (or one of the libraries).

Can you post which versions of conda packages you have installed with `conda list`?

I suspect that we should first have you try the 7.3.0 dev build
```
conda install --yes -c omnia/label/cuda90 openmm==7.3.0
```
which includes debug symbols.

If that still fails, see if you can run a single instance (without MPI) of YANK through a debugger like [`gdb`](https://wiki.python.org/moin/DebuggingWithGdb) to get a more informative stack trace on failure.

**Comment by dtmoustakas** [comment]
Hi John,

here are the conda packages:

# Name                    Version                   Build  Channel
alabaster                 0.7.11                   py36_2    conda-forge
ambermini                 16.16.0                       7    omnia
asn1crypto                0.24.0                   py36_0  
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
babel                     2.6.0                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    2.1.3                      py_0    conda-forge
blosc                     1.14.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cerberus                  1.1                      py36_0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0  
chardet                   3.0.4            py36h0f667ec_1  
clusterutils              0.3.1                    py36_0    omnia
conda                     4.5.4                    py36_0    conda-forge
conda-env                 2.6.0                h36134e3_1  
cryptography              2.2.2            py36h14c3975_0  
curl                      7.60.0                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.28.3           py36hfc679d8_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docopt                    0.6.2                    py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                         0    conda-forge
fftw3f                    3.3.4                         2    omnia
fontconfig                2.13.0                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
glib                      2.53.6               h5d9569c_2  
gmp                       6.1.2                hfc679d8_0    conda-forge
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.6              py36h82fb2a8_1  
imagesize                 1.0.0                    py36_0    conda-forge
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.2.1                    py36_1    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                        0    conda-forge
latexcodec                1.0.5                    py36_0    conda-forge
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                 h470a237_1    conda-forge
libnetcdf                 4.6.1                         2    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.13                 h470a237_0    conda-forge
libxml2                   2.9.8                         0    conda-forge
lzo                       2.10                          0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mdtraj                    1.9.1                    py36_1    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.2                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
more-itertools            4.2.0                      py_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.0              py36_mpich_2    conda-forge
mpich                     3.2.1                         1    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   6.1                  hf484d3e_0  
netcdf4                   1.3.1                    py36_3    conda-forge
notebook                  5.5.0                    py36_0    conda-forge
numexpr                   2.6.5                    py36_0    conda-forge
numpy                     1.14.2           py36hdbf6ddf_1  
numpydoc                  0.8.0                    py36_0    conda-forge
openeye-toolkits          2018.2.1                 py36_0    openeye
openmm                    7.2.2                    py36_1    omnia
openmmtools               0.15.0                   py36_0    omnia
openmoltools              0.8.3                    py36_0    omnia
openssl                   1.0.2o                        0    conda-forge
oset                      0.1.3                    py36_0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.1                   py36_0    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
parmed                    3.0.1                    py36_1    omnia
parso                     0.2.1                      py_0    conda-forge
pcre                      8.41                          1    conda-forge
pdbfixer                  1.5                      py36_0    omnia
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       10.0.1                   py36_0  
pluggy                    0.6.0                      py_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
py                        1.5.3                      py_0    conda-forge
pybtex                    0.21                     py36_0    conda-forge
pybtex-docutils           0.2.1                    py36_0    conda-forge
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
pygments                  2.2.0                    py36_0    conda-forge
pymbar                    3.0.3                    py36_1    conda-forge
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_5    conda-forge
pysocks                   1.6.8                    py36_0  
pytables                  3.4.4                    py36_8    conda-forge
pytest                    3.6.2                    py36_0    conda-forge
python                    3.6.5                hc3d631a_2  
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        5.6.2               hd25b39d_14  
qtconsole                 4.3.1                    py36_0    conda-forge
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py36he2e5f8d_1  
ruamel_yaml               0.15.37          py36h14c3975_2  
scipy                     1.1.0            py36hfc37229_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.2.0                   py36_0  
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0           py36h372c433_1  
snowballstemmer           1.2.1                    py36_0    conda-forge
sphinx                    1.7.5                    py36_0    conda-forge
sphinxcontrib-bibtex      0.4.0                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
sqlite                    3.23.1               he433501_0  
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.7                hc745277_3  
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22             py36hbe7ace6_0  
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.2.1                    py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
yank                      0.22.3                   py36_0    omnia
zeromq                    4.2.5                         1    conda-forge
zlib                      1.2.11               ha838bed_2  

I'll try that version of openmm shortly and will report back.

Thanks!

**Comment by jchodera** [comment]
@dtmoustakas : Have you still been seeing segfaults with SAMS?

**Comment by dtmoustakas** [comment]
After running a few more systems, I've noticed that this crash continues to occur whenever the calculations reach the number of iterations specified in "switch_experiment_interval", and it manifests as an MPI error:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.23.2', 'console_scripts', 'yank')()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/yank/commands/script.py", line 136, in dispatch
    yaml_builder.run_experiments()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 793, in run_experiments
    send_results_to='all')
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/yank/mpi.py", line 511, in distribute
    *other_args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/yank/mpi.py", line 366, in exec_tasks
    raise all_errors[0]
OSError: Group 4/8 Node 1/1: [Errno -101] NetCDF: HDF error: b'sams-twostage-boresch-dense/experiments/SYS1complexligands9/complex.nc'
2018-09-06 10:31:15,287: ERROR - yank.mpi - MPI node 1/8 raised exception.
NoneType: None
2018-09-06 10:31:15,287: CRITICAL - yank.mpi - MPI node 1/8 called Abort()!
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

I've looked in the directory referenced in the OSError line, and this is the tail from the log:

 3.67199584e+01 3.69445971e+01 3.70895047e+01 3.71583638e+01]
2018-09-06 09:20:57,728 - DEBUG - yank.mpi - Node 1/1: waiting for broadcast of <function SAMSSampler._mix_replicas at 0x7f7ed42e8950>
2018-09-06 09:20:57,728 - DEBUG - yank.multistate.multistatesampler - Propagating all replicas...
2018-09-06 09:20:57,728 - DEBUG - yank.mpi - Node 1/1: execute _propagate_replica(0)
2018-09-06 09:20:59,131 - DEBUG - yank.mpi - Node 1/1: sending results of _propagate_replica to 0
2018-09-06 09:20:59,133 - DEBUG - yank.mpi - Node 1/1: execute _get_replica_move_statistics(0)
2018-09-06 09:20:59,133 - DEBUG - yank.mpi - Node 1/1: allgather results of _get_replica_move_statistics
2018-09-06 09:20:59,133 - DEBUG - openmmtools.utils - Propagating all replicas took    1.405s
2018-09-06 09:20:59,133 - DEBUG - yank.mpi - Node 1/1: execute _compute_replica_energies(0)
2018-09-06 09:20:59,298 - DEBUG - yank.mpi - Node 1/1: sending results of _compute_replica_energies to 0
2018-09-06 09:20:59,299 - DEBUG - openmmtools.utils - Computing energy matrix took    0.165s
2018-09-06 09:20:59,299 - DEBUG - yank.mpi - Node 1/1: executing <function MultiStateSampler._report_iteration at 0x7f7ed433cc80>
2018-09-06 09:20:59,299 - DEBUG - yank.mpi - Node 1/1: executing <function SAMSSampler._report_iteration_items at 0x7f7ed42e8840>
2018-09-06 09:20:59,299 - DEBUG - yank.mpi - Node 1/1: executing <function MultiStateSampler._report_iteration_items at 0x7f7ed433cf28>
2018-09-06 09:20:59,299 - DEBUG - yank.multistate.multistatereporter - Iteration 200 not on the Checkpoint Interval of 1000. Sampler State not written.
2018-09-06 09:20:59,303 - DEBUG - openmmtools.utils - Storing sampler states took    0.004s
2018-09-06 09:20:59,453 - DEBUG - openmmtools.utils - Writing iteration information to storage took    0.154s
2018-09-06 09:20:59,453 - DEBUG - yank.multistate.multistatesampler - Iteration took 1.731s.
2018-09-06 09:20:59,453 - DEBUG - yank.multistate.multistatesampler - Estimated completion in 0:00:00, at Thu Sep  6 09:20:59 2018 (consuming total wall clock time 0:05:27.097100).
2018-09-06 09:20:59,454 - DEBUG - yank.mpi - Node 1/1: executing <bound method MultiStateReporter.close of <yank.multistate.multistatereporter.MultiStateReporter object at 0x7f7ec32037f0>>
2018-09-06 09:22:28,824 - DEBUG - yank.mpi - Node 5/8: allgather results of _run_experiment
2018-09-06 09:22:28,849 - WARNING - yank.experiment - The option "processes_per_experiment" will be overwritten as SAMS simulations are currently only compatible with processes_per_experiment=1
2018-09-06 09:22:29,027 - DEBUG - yank.mpi - Group 5/8 Node 1/1: execute _run_experiment(('SYS1complexligands12', {'sampler': 'sams', 'system': 'SYS1-complex_ligands12', 'protocol': 'dense-protocol', 'restraint': {'type': 'PeriodicTorsionBoresch'}}))
2018-09-06 09:56:40,579 - DEBUG - yank.experiment - DSL string for the ligand: "resname MOL"
2018-09-06 09:56:40,579 - DEBUG - yank.experiment - DSL string for the solvent: "auto"
2018-09-06 09:56:40,581 - DEBUG - yank.mpi - Node 1/1: executing <function ExperimentBuilder._save_analysis_script at 0x7f5aca7956a8>
2018-09-06 09:56:40,582 - DEBUG - yank.multistate.multistatereporter - Initial checkpoint file automatically chosen as sams-twostage-boresch-dense/experiments/SYS1complexligands9/complex_checkpoint.nc
2018-09-06 10:31:15,289 - ERROR - yank.mpi - MPI node 4/8 raised exception.
NoneType: None
2018-09-06 10:31:15,289 - CRITICAL - yank.mpi - MPI node 4/8 called Abort()!


I'm currently rerunning this with a different switch_experiment_interval to see if that changes the point at which the calculation crashes.  But I'm a bit at a loss as to what else to look at. 

Thanks!

**Comment by jchodera** [comment]
@andrrizzi : Any ideas about this?

**Comment by andrrizzi** [comment]
It looks to me that opening HDF failed. I've been experiencing random failures when opening the NetCDF file as well at `switch_phase_interval` iterations, but I can't regularly reproduce, and restarting the calculation ends up working, which makes me suspect the fault is in the HDF library rather than YANK.

**Comment by andrrizzi** [comment]
I'll try to make opening the netcdf file opening more robust by making YANK perform several attempts before giving up.

**Comment by jchodera** [comment]
@dtmoustakas : The best we can figure is that there might somehow be a race condition between your (and our!) filesystem being slow to update its records of which files are open/closed, even though the node is calling `Dataset.close()` to close the file before the same (or another) process tries to reopen the file. @andrrizzi and I have some ideas about how to make the file-opening step that's failing more robust. We'll get those improvements into the next YANK update.

In the meantime, could you provide a few small details that may help us track down the root cause?
* Are you writing to a physical disk on the machine, or to a network-mounted filesystem? If network, what kind of filesystem?
* How many MPI processes were you running?
* How many different experiments in the `experiments/` directory were being run in the MPI parallel run?
