### ISSUE TITLE
MPI error with certain group sizes

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1068]
I have 8 processes allocated to 3 MPI calculations, and YANK seems to have trouble dividing processes into communicators:
```
NoneType: None
Traceback (most recent call last):
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/mpi.py", line 384, in _determine_node_color
    node_color = int(self._parent_mpicomm.rank / group_size)
TypeError: unsupported operand type(s) for /: 'int' and 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chodera/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.23.3', 'console_scripts', 'yank')()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/commands/script.py", line 138, in dispatch
    yaml_builder.run_experiments()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 793, in run_experiments
    send_results_to='all')
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/mpi.py", line 504, in distribute
    with _MpiProcessingUnit(group_size) as processing_unit:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/mpi.py", line 299, in __init__
    node_color, n_groups = self._determine_node_color(group_size)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/mpi.py", line 393, in _determine_node_color
    'Group nodes: {}'.format(self._parent_mpicomm.size, group_size))
ValueError: The group division requested cannot be performed.
Total number of nodes: 8
Group nodes: [2, 2, 2]
```
Here is the [YAML file](https://github.com/choderalab/yank-validation/blob/c10c900cd8fe33599c1f16950ff51aec43cbac18/cucurbit7uril/repex.yaml) and [LSF submission script](https://github.com/choderalab/yank-validation/blob/c10c900cd8fe33599c1f16950ff51aec43cbac18/cucurbit7uril/run-lsf-repex.sh).

**Comment by jchodera** [comment]
I think this is the same issue as #1012.
