### ISSUE TITLE
YAML files written by `yank analyze --serial` are not readable

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1082]
To reproduce:
```
>>> import yaml
>>> x = yaml.load(open('reports/Harmonic_cmethingesinglehinge0_neutral-sams-rmsd.pkl', 'r'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 578, in construct_python_object
    state = self.construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 93, in construct_object
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 578, in construct_python_object
    state = self.construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 93, in construct_object
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 93, in construct_object
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 93, in construct_object
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 578, in construct_python_object
    state = self.construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 93, in construct_object
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 93, in construct_object
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 578, in construct_python_object
    state = self.construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 93, in construct_object
    for dummy in generator:
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yaml/constructor.py", line 61, in construct_object
    "found unconstructable recursive node", node.start_mark)
yaml.constructor.ConstructorError: found unconstructable recursive node
  in "reports/Harmonic_cmethingesinglehinge0_neutral-sams-rmsd.pkl", line 215, column 19
```
I've attached the test input in zip format.
(Apologies for accidentally adding the `.pkl` suffix.)

[yaml.zip](https://github.com/choderalab/yank/files/2363876/yaml.zip)

Pinging @lnaden in case he has any suggestions for debugging.

**Comment by Lnaden** [comment]
I'm pretty sure those are pickle files. Not YAML

**Comment by jchodera** [comment]
@Lnaden : They're YAML files!

[notpickle.zip](https://github.com/choderalab/yank/files/2367649/notpickle.zip)

I know---I was surprised too! But that's definitely a YAML file.

[`MultiExperimentaAnalyzer._serialize()` dumps a pickle](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L913-L926), but this [other guy dumps a YAML](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L684-L698) and is somehow being called instead. Should that *also* be a pickle?

**Comment by Lnaden** [comment]
Ah. The serialization line is used by the Jupyter Notebooks to dump their data to file. The problem is the Numpy arrays are bing dumped as arrays, instead of as lists. Since we have been using the MultiAnalyzer for everything else, this probably slipped through as I removed most (all?) of the `ndarray.to_list` calls on serialization since I was just pickling up the data anyways.
