### ISSUE TITLE
Yank 0.23.5 netCDF4 Index Error

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#1100]
Hi there, I was testing the latest Yank release 0.23.5. I was performing solvation free energy calculation on phenol. I stopped the system after 100 iterations to compute the free energy and then I restarted the system till 300 yank iterations. Unfortunately around 200 iterations, Yank was generating the following error:

```Traceback (most recent call last):
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/bin/yank", line 11, in <module>
   load_entry_point('yank==0.23.5', 'console_scripts', 'yank')()
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/cli.py", line 73, in main
   dispatched = getattr(commands, command).dispatch(command_args)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/commands/script.py", line 138, in dispatch
   yaml_builder.run_experiments()
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/experiment.py", line 791, in run_experiments
   completed[exp_index] = self._run_experiment(exp)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/experiment.py", line 3124, in _run_experiment
   built_experiment.run(n_iterations=switch_experiment_interval)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/experiment.py", line 476, in run
   alchemical_phase.run(n_iterations=iterations_to_run)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/yank.py", line 1209, in run
   self._sampler.run(n_iterations=n_iterations)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistatesampler.py", line 685, in run
   self._report_iteration()
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/mpi.py", line 271, in _wrapper
   return run_single_node(rank, task, *args, **kwargs)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/mpi.py", line 220, in run_single_node
   result = task(*args, **kwargs)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/mpi.py", line 621, in _delayed_termination
   return func(*args, **kwargs)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/openmmtools/utils.py", line 87, in _wrapper
   return func(*args, **kwargs)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistatesampler.py", line 1104, in _report_iteration
   self._reporter.write_timestamp(self._iteration)
 File "/home/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.5/site-packages/yank/multistate/multistatereporter.py", line 996, in write_timestamp
   self._storage_checkpoint.variables['timestamp'][checkpoint_iteration] = timestamp
 File "netCDF4/_netCDF4.pyx", line 4299, in netCDF4._netCDF4.Variable.__setitem__
 File "netCDF4/_netCDF4.pyx", line 4213, in netCDF4._netCDF4.Variable._assign_vlen
IndexError: data can only be assigned to VLEN variables using integer indices
2018-10-02 14:35:36,695: Single node: executing <bound method MultiStateReporter.close of <yank.multistate.multistatereporter.MultiStateReporter object at 0x7f9279adf400>>```

This has happened multiple times already at different number of Yank iterations in different runs. I have attached the last yank run data here: 

https://drive.google.com/open?id=1-4_d-cNyx2SWqlr2s4DGoQ2GuBIkewO9

Please let me know if you need further info

**Comment by andrrizzi** [comment]
I've noticed this
```yaml
options:
    ...
    checkpoint_interval: 300
```
Did you change the `checkpoint_interval` after running the first 100 iterations? If so, it should be ignored, but maybe it's causing some problems we haven't seen before.

**Comment by nividic** [comment]
YES I changed it from 100 to 300

**Comment by andrrizzi** [comment]
That may be the problem. It's not possible to change the checkpoint interval during the simulation or the analysis would be much harder to perform. The reporter should handle that gracefully and just use the checkpoint interval used during creation, but probably it's not doing it correctly.

**Comment by nividic** [comment]
@andrrizzi Thanks for you prompt reply. Just to clarify. Suppose that I want to run SFEC/ABFE on a system in the following way:

(1) stop at 20 iterations
(2) Process the data 1-20 iterations.
(3) restart and stop to 100 iterations.
(4) Process data 1-100 iterations.
(5) restart and stop 1000 iterations.
(6) Process 1-1000 iterations. 

How can I do that now? Thank you so much

**Comment by andrrizzi** [comment]
That's tricky, unfortunately. With the way the checkpoint interval works, you'll have to keep `checkpoint_interval=20` the whole time and just increase `number_of_iterations` to 100 and 1000. If you're concerned about the size of the checkpoint interval, you may turn on online analysis, but I think that will give you only the free energy in the log, not the full notebook analysis. @Lnaden and @jchodera may have other suggestions though.

**Comment by jchodera** [comment]
@andrizzi's suggestion matches mine! Just keep the checkpoint interval at 20 if your shortest run length is 20.

Also, I would definitely use longer run lengths than 20 iterations! A simulation that short will not be useful.

**Comment by nividic** [comment]
I repeated the previous simulation this time without changing the ```checkpoint_interval=20``` between the restarting but I'm still getting the same error. Just to clarify:

(1) In my original yank yaml file I was setting the flags: ```minimize=yes resume_simulation=no resume_setup=no number_of_iterations=20```
(2) after the first 20 yank iterations I was setting the flag: ```minimize=no resume_simulation=yes resume_setup=yes number_of_iterations=100```

Around ~40 iterations the error was triggered again. As I said before I was not changing the ```checkpoint_interval=20``` flag between the restarting

**Comment by jchodera** [comment]
Can you share the two complete YAML input files you used?

**Comment by nividic** [comment]
@jchodera I have attached the files. After calling the first run_20.yaml file I was calling the second file run_100.yaml file. I re-checked and still around ~ 40 iterations Yank was crashing...so it seems to be reproducible. I left the simulation run files as well. 
[TEST_YANK_ANALYSIS.zip](https://github.com/choderalab/yank/files/2443286/TEST_YANK_ANALYSIS.zip)

**Comment by jchodera** [comment]
Hm, I don't see why this shouldn't work.
@andrizzi: Can you try to reproduce from these test files?

**Comment by andrrizzi** [comment]
I'll try to reproduce this!

**Comment by andrrizzi** [comment]
Found it! I'll make another bugfix release. Thanks for reporting this!

**Comment by nividic** [comment]
@nividic @jchodera Thanks a lot
