### ISSUE TITLE
CRITICAL logs show unusual exception

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1108]
The `_CRITICAL.log`s I see contain
```
2018-10-12 23:14:51,070 - CRITICAL - yank.mpi - MPI node 1/12 raised an exception and called Abort()! The exception traceback follows


Traceback (most recent call last):
  File "run_yank.py", line 153, in <module>
    main(args.yaml_script_path, args.job_id, args.n_jobs)
  File "run_yank.py", line 141, in main
    experiment_builder.run_experiments()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 796, in run_experiments
    send_results_to='all')
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/mpi.py", line 531, in distribute
    *other_args, **kwargs)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/mpi.py", line 386, in exec_tasks
    raise error
AttributeError: Group 1/12 Node 1/1 received an exception from another MPI process. Original stack trace follow:
Traceback (most recent call last):
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/mpi.py", line 357, in exec_tasks
        results.append(task(distributed_arg, *other_args, **kwargs))
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 3120, in _run_experiment
        built_experiment.run(n_iterations=switch_experiment_interval)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 460, in run
        alchemical_phase = AlchemicalPhase.from_storage(phase)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/yank.py", line 811, in from_storage
        sampler = sampler_class.from_storage(storage)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/multistate/multistatesampler.py", line 222, in from_storage
        sampler = cls._instantiate_sampler_from_reporter(reporter)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/multistate/multistatesampler.py", line 854, in _instantiate_sampler_from_reporter
        options['mcmc_moves'] = reporter.read_mcmc_moves()
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank/multistate/multistatereporter.py", line 748, in read_mcmc_moves
        mcmc_moves.append(mmtools.utils.deserialize(serialized_move))
      File "/home/chodera/miniconda/lib/python3.6/site-packages/openmmtools/utils.py", line 597, in deserialize
        names.append(serialization.pop(_SERIALIZED_MANGLED_PREFIX + key))
    AttributeError: 'NoneType' object has no attribute 'pop
```
I have installed
```
openmm                    7.4.0             py36_cuda92_1    omnia/label/dev
openmmtools               0.15.0                   py36_0    omnia
yank                      0.23.7                   py36_0    omnia
```
with openmm `7.3.0.dev-f8dcb72`.

**Comment by jchodera** [comment]
Actually, this may not be related to NaNs at all.

**Comment by jchodera** [comment]
Great detective work! I wonder if there's a way we can raise an exception if the NetCDF file is corrupted.

I'll spend more time investigating the "safe termination" as discussed in https://github.com/choderalab/yank/issues/1081

**Comment by andrrizzi** [comment]
> I wonder if there's a way we can raise an exception if the NetCDF file is corrupted.

We usually do, but in cases like this is hard because netcdf doesn't raise an exception. It just returned an empty string for some reason. Closing this for now.

**Comment by jchodera** [comment]
Could we add error checking for empty strings being returned in this particular case? This seems to occur in multiple different NetCDF files for me.
