### ISSUE TITLE
Error in abort

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1117]
I had a repex job abort at the end of a trailblazing run---after all experiments had seemingly completed trailblazing but not proceeded to simulation---and give a weird error message:
```
2018-10-24 03:54:23,626 - DEBUG - yank.mpi - Node 1/1: waiting for barrier after <function ExperimentBuilder._generate_yaml at 0x2ae94b766d08>
2018-10-24 05:08:12,836 - CRITICAL - yank.mpi - MPI node 8/16 raised an exception and called Abort()! The exception traceback follows
Traceback (most recent call last):
  File "/home/chodera/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.23.8', 'console_scripts', 'yank')()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/commands/script.py", line 138, in dispatch
    yaml_builder.run_experiments()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/experiment.py", line 778, in run_experiments
    self._generate_experiments_protocols()
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/experiment.py", line 2452, in _generate_experiments_protocols
    send_results_to=None, group_size=1, sync_nodes=True)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/mpi.py", line 531, in distribute
    *other_args, **kwargs)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/mpi.py", line 386, in exec_tasks
    raise error
TypeError: Group 8/16 Node 1/1 received an exception from another MPI process. Original stack trace follow:
Traceback (most recent call last):
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/mpi.py", line 357, in exec_tasks
        results.append(task(distributed_arg, *other_args, **kwargs))
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/experiment.py", line 2548, in _generate_experiment_protocol
        alchemical_phase = phase.initialize_alchemical_phase()
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/experiment.py", line 359, in initialize_alchemical_phase
        alchemical_phase.equilibrate(n_iterations, mcmc_moves=mcmc_move)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/yank.py", line 1197, in equilibrate
        self._sampler.equilibrate(n_iterations=n_iterations, mcmc_moves=mcmc_moves)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/multistate/multistatesampler.py", line 616, in equilibrate
        self._propagate_replicas()
      File "/home/chodera/miniconda/lib/python3.6/site-packages/openmmtools-0.17.0-py3.6.egg/openmmtools/utils.py", line 87, in _wrapper
        return func(*args, **kwargs)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/multistate/multistatesampler.py", line 1195, in _propagate_replicas
        send_results_to=0)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/mpi.py", line 531, in distribute
        *other_args, **kwargs)
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/mpi.py", line 376, in exec_tasks
        raise error
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/mpi.py", line 357, in exec_tasks
        results.append(task(distributed_arg, *other_args, **kwargs))
      File "/home/chodera/miniconda/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/multistate/multistatesampler.py", line 1226, in _propagate_replica
        output_dir = os.path.join(os.path.dirname(self._reporter.filepath), 'nan-error-logs')
      File "/home/chodera/miniconda/lib/python3.6/posixpath.py", line 156, in dirname
        p = os.fspath(p)
    TypeError: Node 1/1: expected str, bytes or os.PathLike object, not method
```

**Comment by andrrizzi** [comment]
Fixed in #1127.
