### ISSUE TITLE
Test error when using new openmmtools release

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1133]
The YANK tests are failing on Python 3.6 with [this openmmtools error](https://travis-ci.org/choderalab/yank/jobs/484928683#L3601-L3612):
```
======================================================================
ERROR: Any property of the ThermodynamicSystem can be specified in the protocol.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/tests/test_yank.py", line 433, in test_non_alchemical_protocol
    protocol, storage_path, restraint=yank.restraints.Harmonic())
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/yank-0.23.8-py3.6-linux-x86_64.egg/yank/yank.py", line 1046, in create
    'have protocol attribute {}'.format(lambda_key))
AttributeError: CompoundThermodynamicState object does not have protocol attribute update_alchemical_charges
-------------------- >> begin captured logging << --------------------
```
I'm worried that this may be caused by the update to [openmmtools 0.17.0](https://travis-ci.org/choderalab/yank/jobs/484928683#L1791).

**Comment by jchodera** [comment]
I've tested YANK with the new `openmmtools` 0.17.0 release on [an updated T4 lysozyme L99A validation test](https://github.com/choderalab/yank-validation/pull/12) and found it runs fine, so I am downgrading this bug from critical.
