### ISSUE TITLE
Docs deployment is broken

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1187]
It looks like the nightly dev build docs aren't deploying via travis:
```
Installing deploy dependencies
Logging in with Access Key: ****************FVPQ
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-s3-1.10.13/lib/dpl/provider/s3.rb:71:in `chdir': No such file or directory @ dir_chdir - docs/_deploy (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-s3-1.10.13/lib/dpl/provider/s3.rb:71:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-s3-1.10.13/lib/dpl/provider/s3.rb:124:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
dpl.3
Deploying application
failed to deploy
```
I'm not sure we _need_ nightly build docs deployment. Any thoughts, @andrrizzi?

**Comment by andrrizzi** [comment]
> I'm not sure we need nightly build docs deployment.

I agree. I think we could push the docs only on release if it's easy to automate.
