### ISSUE TITLE
Trailblazing analysis error

### ISSUE THREAD

**Issue by mjw99** [choderalab/yank#1214]
Dear Authors,

I am currently attempting some trailblazing calculations using YANK for a screen of some drug fragments against the SARS-CoV-2 main protease. The repo is [here](https://github.com/mjw99/COVID_19_Drug_Binding).  

I am seeing this (as of commit c991b54) on the analysis of the x0072-explicit-trailblazing.yaml run: 
```
yank analyze --store=./x0072-explicit-trailblazing-output/experiments/

(openmm) [mw529@login-e-6 COVID_19_Drug_Binding]$ yank analyze --store=./x0072-explicit-trailblazing-output/experiments/
/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/analyze.py:299: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  analysis = yaml.load(f)
2020-03-22 21:29:22,651: WARNING - openmmtools.multistate.multistatereporter - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-03-22 21:29:22,777: WARNING - openmmtools.multistate.multistateanalyzer - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-03-22 21:29:22,781: WARNING - openmmtools.multistate.multistatereporter - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-03-22 21:29:22,820: WARNING - openmmtools.multistate.multistateanalyzer - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-03-22 21:29:23,353: WARNING - yank.analyze - Alert: analyzed timeseries has the same or fewer number of values as discard_from_start! The whole series has been preserved to ensure there is *something* to analyze.
/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/mw529/.conda/envs/openmm/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/analyze.py", line 783, in analyze_directory
    analysis_data = auto_experiment_analyzer.auto_analyze()
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/analyze.py", line 173, in make_copy
    return copy.deepcopy(wrap(*args, **kwargs))
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/analyze.py", line 703, in auto_analyze
    _ = self.get_equilibration_data()
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/analyze.py", line 173, in make_copy
    return copy.deepcopy(wrap(*args, **kwargs))
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/yank/analyze.py", line 452, in get_equilibration_data
    i_t, g_i, n_effective_i = mmtools.multistate.get_equilibration_data_per_sample(self.u_ns[phase_name])
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/openmmtools/multistate/utils.py", line 170, in get_equilibration_data_per_sample
    g_i = np.ones([max_subset], np.float32)
  File "/home/mw529/.conda/envs/openmm/lib/python3.7/site-packages/numpy/core/numeric.py", line 207, in ones
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed 
```
I suspect the key part is:
```
"2020-03-22 21:36:40,185: WARNING - yank.analyze - Alert: analyzed timeseries has the same or fewer number of values as discard_from_start! The whole series has been preserved to ensure there is *something* to analyze." 
```
which I think is thrown from [here](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L445). I am still finding my way around the code and I suspect at this point, it may be user error on my behalf.

Any suggestions or tips would be really useful.

**Comment by andrrizzi** [comment]
Hi @mjw99. I suspect something has gone wrong with the simulation. Can you check in the log that both the complex and solvent phase of the calculation completed correctly?

**Comment by mjw99** [comment]
Thanks for looking at this. This is a [link](https://drive.google.com/open?id=1cYYWRqbb0jI9yESfNphhhb7XU0x46DTF) to the logfile. I can't see anything obvious offhand. Is there any more I can provide to help?

**Comment by mjw99** [comment]
Is the line about
```
Could not access file 'x0072-explicit-trailblazing-output/experiments/trailblaze/complex/coordinates.dcd'.
```
a problem?

**Comment by andrrizzi** [comment]
Ah, sorry for missing it. I think this is the problem: https://github.com/mjw99/COVID_19_Drug_Binding/blob/master/x0072-explicit-trailblazing.yaml#L10 (`default_number_of_iterations: 0`).

In the example that I sent you, I set it to 0 only because I just wanted to run trailblaze and check the resulting protocol, but you'll have to increase it to run some HREX iterations like in the "non-trailblazed" calculation.

**Comment by mjw99** [comment]
Many thanks; I'll test that now. Any ideas on a good value for default_number_of_iterations in this type of calculation?

**Comment by andrrizzi** [comment]
It depends on the system, but I'd start with 5000 (i.e. 5ns/replica with your settings). You can start with a smaller number anyway since you can extend it later. Just make sure that it is a multiple of `checkpoint_interval`, which is the number of iterations between the creation of two restart checkpoints.

**Comment by mjw99** [comment]
Perfect; I'll test that now. Thanks again.

**Comment by mjw99** [comment]
The suggestion of setting default_number_of_iterations to a non zero value has worked. I tried a small value of 100 yesterday and "it worked", with respect to not triggering the error initially stated in this ticket, but failed in the analysis with the standard "Warning: Should have \sum_n W_nk = 1..." error.

I am just going to experiment a bit with with a larger value for default_number_of_iterations and perhaps a smaller value of clearance for the solvent. My main constraint at the moment is the max wallclock time for the job.

Thank you again for the advice Andrea. 

I think this can be closed.

**Comment by mjw99** [comment]
Hmm, having seen a failure of  
```
Warning: Should have \sum_n W_nk = 1
...
```
with default_number_of_iterations: 400 and a smaller solvent clearance value. I read a few other tickets [here](https://github.com/choderalab/yank/issues/1203) and I rolled my pymbar from 3.0.5 to 3.0.3. Rerunning, I obtained a result, and not an error as before:
```
Free energy of binding  :     0.556 +- 1.792 kT (0.331 +- 1.068 kcal/mol)
DeltaG complex          :   278.014 +- 1.630 kT
DeltaG standard state correction:             -4.394 kT
DeltaG solvent          :   274.176 +- 0.744 kT

Enthalpy of binding     :   800.007 +- 41.105 kT (476.934 +- 24.505 kcal/mol)

```

**Comment by hannahbrucemacdonald** [comment]
Pleased that rolling back pymbar helped. 400 iterations (0.4ns per iteration) is still quite short, and in the regime of equilibration really. Are you able to run for longer?

If wallclock time is the limitation at the moment, as @andrrizzi mentioned, you can always restart simulations from the checkpoint to stretch the simulation time out longer!

**Comment by mjw99** [comment]
Hi Hannah,

Thank you for this; agreed that 400 iterations, even with HMR and a longer integration step, will be too short. I'm going to profile the performance of the system and try a few more things.

I think the restart option will be the way to go; many thanks for the suggestion.

Thanks,

Mark

**Comment by andrrizzi** [comment]
Another thing that might work is to increase the `thermodynamic_distance` parameter of thermodynamic trailblazing from 2.0 (kT) to something like 2.5 or 3.0. It should generate a smaller number of intermediate states, but the advantage of using that algorithm is that they will be nearly optimally spaced so that the statistic can tolerate a sparser protocol.
