### ISSUE TITLE
mpi4py should be a dependency of conda installer

### ISSUE THREAD

**Issue by daveminh** [choderalab/yank#1215]
I got this error from a fresh install from miniconda3 when running on XSEDE Bridges.

Traceback (most recent call last):
  File "/home/dminh/.conda/envs/yank/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/dminh/.conda/envs/yank/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/dminh/.conda/envs/yank/lib/python3.7/site-packages/yank/commands/script.py", line 147, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/dminh/.conda/envs/yank/lib/python3.7/site-packages/yank/experiment.py", line 591, in __init__
    self.parse(script)
  File "/home/dminh/.conda/envs/yank/lib/python3.7/site-packages/yank/experiment.py", line 684, in parse
    utils.config_root_logger(self._options['verbose'], log_file_path=None)
  File "/home/dminh/.conda/envs/yank/lib/python3.7/site-packages/yank/utils.py", line 132, in config_root_logger
    mpicomm = mpiplus.get_mpicomm()
  File "/home/dminh/.conda/envs/yank/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 122, in get_mpicomm
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'

**Comment by jchodera** [comment]
The [yank recipe](https://github.com/omnia-md/conda-recipes/blob/master/yank/meta.yaml#L29) requires [`mpiplus`](http://github.com/choderalab/mpiplus). We migrated the recipe to conda-forge, but it appears we [neglected to include that dependency](https://github.com/conda-forge/mpiplus-feedstock/blob/master/recipe/meta.yaml). Could you refile the issue that mpiplus should require mpi4py [here](https://github.com/conda-forge/mpiplus-feedstock/issues)?

cc @andrrizzi

**Comment by andrrizzi** [comment]
Hmm. This shouldn't happen. `mpiplus` should be a requirement of `openmmtools` so there should be no need to include it in yank's recipe.

**Comment by andrrizzi** [comment]
Oh, I see, it's the `mpiplus` recipe that needs to include the python `mpi4py` package. Yes, I agree (cc @hannahbrucemacdonald).
