### ISSUE TITLE
How to configure yank script when the receptor includes coenzyme

### ISSUE THREAD

**Issue by kingljy0818** [choderalab/yank#1223]
Dear all,

Recently I found that yank could not calculate free energy when the pdb of the receptor contains coenzyme such as FAD (PDB ID: 4kw5), but this fad interacts with the ligand, would ask how to configure the yank script yaml in the situation above. Many thanks.

Kindest regards

Jiyuan

**Comment by andrrizzi** [comment]
Hi Jiyuan. Can your input files and the error you get?

Worst case scenario, you can skip YANK's automatic pipeline and prepare the topology/coordinate files yourself (see tutorial: http://getyank.org/latest/tutorial.html#when-the-automatic-pipeline-won-t-do).

**Comment by kingljy0818** [comment]
Hi andrrizzi. In fact, I am an older user of the MD software amber, the coenzyme in PDB (4kw5), I have already used amber to make .frcmod and .lib files, would you tell me how to add them into the parameter of yaml script and to make Yank recognize. Many thanks.

**Comment by kingljy0818** [comment]
Hi,
I encountered a trouble with running absolute-binding protocol on a system that was prepared with AMBER and should work according to the instructions provided online.

Here is my yaml script:
--------------------------------------------------------------------------------------------------------------
options:
  minimize: yes
  verbose: yes
  number_of_equilibration_iterations: 100
  default_number_of_iterations: 5
  nsteps_per_iteration: 1000
  temperature: 300*kelvin
  pressure: 1*atmosphere
  timestep: 2*femtoseconds
  platform: CUDA
  output_dir: tca1-dpre-explicit-output

solvents:
  tip4pew:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms

systems:
  dpre-tca1:
  phase1_path: [input/com.prmtop, input/com.inpcrd]
  phase2_path: [input/sol.prmtop, input/sol.inpcrd]
  solvent: tip4pew
  ligand_dsl: resname 459

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
        # Set lambda restraints reverse of coupling parameter.
        lambda_restraints:     [0.00, 0.25, 0.50, 0.75, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]

experiments:
  system: dpre-tca1
  protocol: absolute-binding
  restraint:
    type: Harmonic
--------------------------------------------------------------------------------------------------------------

When I run this file, I got this error:

Traceback (most recent call last):
  File "/home/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/commands/script.py", line 147, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 591, in __init__
    self.parse(script)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 672, in parse
    yaml_content = self._expand_systems(yaml_content)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 1075, in _expand_systems
    expanded_content = expanded_content.expand_id_nodes('systems', update_nodes_paths)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 508, in expand_id_nodes
    in id_node_val.named_combinations(separator='_', max_name_length=30)}
  File "/home/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 507, in <dictcomp>
    combinations = {id_node_key + '_' + name: comb for name, comb
  File "/home/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 404, in named_combinations
    leaf_paths, leaf_vals = self._find_combinatorial_leaves()
  File "/home/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 645, in _find_combinatorial_leaves
    leaf_paths, leaf_vals = self._find_leaves()
  File "/home/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 631, in _find_leaves
    return recursive_find_leaves(self._d)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 620, in recursive_find_leaves
    for child_key, child_val in node.items():
AttributeError: 'NoneType' object has no attribute 'items'

Would you help solve this problem, many thanks.

**Comment by andrrizzi** [comment]
The indentation here seems off to me:
```
systems:
  dpre-tca1:
  phase1_path: [input/com.prmtop, input/com.inpcrd]
  phase2_path: [input/sol.prmtop, input/sol.inpcrd]
  solvent: tip4pew
  ligand_dsl: resname 459
```
The last four keywords should have an extra level of indentation. Could this be the problem?
