### ISSUE TITLE
yank analyze error in restraint energy calculation

### ISSUE THREAD

**Issue by isjoung** [choderalab/yank#1234]
Hi,
I encounter an error in yank analysis. The problem is caused by the atomic weights because the Quantity instance cannot be cast to a float. Please see the traces below.
```
$ yank analyze -s output/experiments/
/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/analyze.py:299: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  analysis = yaml.load(f)
2020-06-07 01:02:36,806: WARNING - openmmtools.multistate.multistatereporter - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-06-07 01:02:36,846: WARNING - openmmtools.multistate.multistateanalyzer - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-06-07 01:02:36,848: WARNING - openmmtools.multistate.multistatereporter - Warning: The openmmtools.multistate API is experimental and may change in future releases
2020-06-07 01:02:36,866: WARNING - openmmtools.multistate.multistateanalyzer - Warning: The openmmtools.multistate API is experimental and may change in future releases
Traceback (most recent call last):
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 403, in __get__
    value = instance._cache[self.name]
KeyError: 'mbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 403, in __get__
    value = instance._cache[self.name]
KeyError: 'unbiased_decorrelated_u_ln'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 1756, in _compute_restraint_energies
    distance = restraint_force.distance_at_energy(potential_energy) / _MDTRAJ_DISTANCE_UNIT
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/forces.py", line 977, in distance_at_energy
    raise ValueError('Cannot compute the distance at this potential energy.')
ValueError: Cannot compute the distance at this potential energy.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/insukjoung/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 783, in analyze_directory
    analysis_data = auto_experiment_analyzer.auto_analyze()
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 173, in make_copy
    return copy.deepcopy(wrap(*args, **kwargs))
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 705, in auto_analyze
    _ = self.get_experiment_free_energy_data()
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 173, in make_copy
    return copy.deepcopy(wrap(*args, **kwargs))
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 565, in get_experiment_free_energy_data
    data[phase_name] = analyzer.analyze_phase()
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 151, in analyze_phase
    Deltaf_ij, dDeltaf_ij = self.get_free_energy()
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 1924, in get_free_energy
    self._compute_free_energy()
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 1877, in _compute_free_energy
    nstates = self.mbar.N_k.size
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 405, in __get__
    value = self._get_default(instance)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 426, in _get_default
    value = self._default(self, instance)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 2122, in mbar
    return instance._create_mbar(instance._unbiased_decorrelated_u_ln,
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 405, in __get__
    value = self._get_default(instance)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 426, in _get_default
    value = self._default(self, instance)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 2102, in _unbiased_decorrelated_u_ln
    return instance._compute_mbar_unbiased_energies()[0]
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 1562, in _compute_mbar_unbiased_energies
    weights_group2)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 1775, in _compute_restraint_energies
    weights_group1, weights_group2)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/openmmtools/multistate/multistateanalyzer.py", line 85, in compute_centroid_distance
    com_group1 = np.average(positions_group1, axis=0, weights=weights_group1)
  File "<__array_function__ internals>", line 6, in average
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 425, in average
    avg = np.multiply(a, wgt, dtype=result_dtype).sum(axis)/scl
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/numpy/ma/core.py", line 4157, in __truediv__
    return true_divide(self, other)
  File "/home/insukjoung/anaconda3/lib/python3.7/site-packages/numpy/ma/core.py", line 1171, in __call__
    m = ~umath.isfinite(result)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by andrrizzi** [comment]
Hi @isjoung. I have never seen that error before. Could you share the YAML file used to run the calculation?

**Comment by isjoung** [comment]
This is the YAML file.

options:
  verbose: yes
  setup_dir: setup
  output_dir: output
  experiments_dir: experiments
  randomize_ligand: yes
  minimize: yes
  default_number_of_iterations: 2000
  temperature: 300*kelvin
  pressure: null

solvents:
  GBSA:
    nonbonded_method: NoCutoff
    implicit_solvent: OBC2
    solvent_dielectric: 78.5

systems:
  protein-ligand-complex:
    phase1_path: [ complex.nosolv.prmtop, complex.nosolv.inpcrd ]
    phase2_path: [ ligand.nosolv.prmtop, ligand.nosolv.inpcrd ]
    ligand_dsl: resname LIG
    solvent: GBSA

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.00]

experiments:
  system: protein-ligand-complex
  protocol: absolute-binding
  restraint:
    type: FlatBottom
    well_radius: 3.0 * nanometers

**Comment by andrrizzi** [comment]
I don't understand why you are getting that error, but could you try analyzing the results adding the option `yank analyze --skipunbiasing ...`?

Because you are not specifying `lambda_restraints` in the alchemical path of the complex phase, the flat bottom restraint remains activated throughout the simulation and YANK attempts to remove the the bias introduced by the restraint during the analysis. With that option you skip that part. Hopefully, using the flat-bottom restraint won't bias the final free energy too much.

Alternatively, you can use a protocol like this
```yaml
alchemical_path:
  lambda_restraints: [0.0, 1.0, 1.0, ...]
  lambda_electrostatics: [1.0, 1.0, 0.95, ...]
  lambda_sterics: [1.0, 1.0, 1.0, ...]
```
and YANK won't need to run the unbiasing part of the analysis.

**Comment by isjoung** [comment]
Ah, you are right. I forgot the restraint part.
`--skipunbiasing` works fine without an error.
Thank you!

**Comment by andrrizzi** [comment]
Glad it worked!
