### ISSUE TITLE
How to use yank for peptide-protein binding?

### ISSUE THREAD

**Issue by aizvorski** [choderalab/yank#1240]
I'd like to use yank to calculate binding free energy for a peptide binding to a protein.  I'm not sure if this is a supported use case, but I gave it a try and ran into some errors.

My starting point was the yank-examples 1.1.0 binding/abl-imatinib/ .  I changed implicit.yaml like this:

```
molecules:
  myprotein:
    filepath: input/myprotein.pdb
  mypeptide:
    filepath: input/mypeptide.pdb

...

systems:
  myprotein_peptide:
    receptor: myprotein
    ligand: mypeptide
    solvent: GBSA
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.gaff2, leaprc.water.tip4pew]

...

experiments:
  system: myprotein_peptide
  protocol: absolute-binding
```
(rest same as the original)
and ran yank script --yaml=implicit.yaml

The result looks like this:

```
2020-08-21 02:18:10,991: Single node: executing <function ExperimentBuilder._check_resume at 0x7f4f09f95830>
2020-08-21 02:18:10,992: Running _setup_molecules serially.
2020-08-21 02:18:10,992: Running get_system serially.
2020-08-21 02:18:10,992: Setting up the systems for ace2 and peptide using solvent GBSA
2020-08-21 02:18:10,992: Setting up solvent phase
2020-08-21 02:18:11,386: WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: 2.000000 is not zero.
2020-08-21 02:18:11,386: WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: 2.000000 is not zero.
2020-08-21 02:18:11,387: Setting up complex phase
2020-08-21 02:18:14,701: WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: -25.000000 is not zero.
2020-08-21 02:18:14,701: WARNING - yank.pipeline - TLeap: The unperturbed charge of the unit: -25.000000 is not zero.
2020-08-21 02:18:14,702: Single node: executing <function ExperimentBuilder._generate_yaml at 0x7f4f09f95ef0>
2020-08-21 02:18:14,714: Running _generate_experiment_protocol serially.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 751, in run_experiments
    completed[exp_index] = self._run_experiment(exp, write_status=write_status)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 3247, in _run_experiment
    built_experiment = self._build_experiment(experiment_path, experiment)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 3042, in _build_experiment
    ligand_resname = utils.Mol2File(ligand_descr['filepath']).resname
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 1124, in resname
    return next(self.resnames)
StopIteration
```

Looking a bit at the code, it looks like this is trying to read the input/mypeptide.pdb file as a mol2 file (and failing).

The amber tools seemed to run okay though, there are a bunch of files in implicit/setup/systems/myprotein_peptide/ including some .prmtop and .inpcrd files.

Is what I'm trying to do possible?  If yes, how should I do it?

**Comment by andrrizzi** [comment]
Hi @aizvorski. The setup of peptide-peptide systems is not supported by the YANK automatic pipeline, but you can set up the system with an alternative pipeline and feed the built system to YANK: http://getyank.org/latest/tutorial.html#when-the-automatic-pipeline-won-t-do
