### ISSUE TITLE
AttributeError: module 'simtk.openmm.app.forcefield' has no attribute '_matchResidue'

### ISSUE THREAD

**Issue by tengjieksee** [choderalab/yank#1241]
Hi, I was trying to run the setup-protein.sh with my own protein in the example folder "t4-lysozyme". Here's the error,

Preparing receptor by adding missing atoms...
Traceback (most recent call last):
  File "/vcp1/ustudent/tsee0001/.conda/envs/yanky_v3/bin/pdbfixer", line 6, in <module>
    sys.exit(pdbfixer.pdbfixer.main())
  File "/vcp1/ustudent/tsee0001/.conda/envs/yanky_v3/lib/python3.6/site-packages/pdbfixer/pdbfixer.py", line 1238, in main
    fixer.addMissingAtoms()
  File "/vcp1/ustudent/tsee0001/.conda/envs/yanky_v3/lib/python3.6/site-packages/pdbfixer/pdbfixer.py", line 903, in addMissingAtoms
    forcefield = self._createForceField(newTopology, False)
  File "/vcp1/ustudent/tsee0001/.conda/envs/yanky_v3/lib/python3.6/site-packages/pdbfixer/pdbfixer.py", line 1125, in _createForceField
    if any(app.forcefield._matchResidue(residue, t, bondedToAtom) is not None for t in forcefield._templateSignatures[signature]):
  File "/vcp1/ustudent/tsee0001/.conda/envs/yanky_v3/lib/python3.6/site-packages/pdbfixer/pdbfixer.py", line 1125, in <genexpr>
    if any(app.forcefield._matchResidue(residue, t, bondedToAtom) is not None for t in forcefield._templateSignatures[signature]):
AttributeError: module 'simtk.openmm.app.forcefield' has no attribute '_matchResidue'

Any help would be greatly appreciated! :(

**Comment by andrrizzi** [comment]
Hi @tengjieksee . I think I saw that error before. It seems to be pdbfixer from the stack. Maybe that script is missing the call to `fixer.findMissingAtoms()` before `fixer.addMissingAtoms()`? I think taking a look at the pdbfixer manual should help anyway: http://htmlpreview.github.io/?https://raw.github.com/pandegroup/pdbfixer/master/Manual.html .

**Comment by mainguyenanhvu** [comment]
I guess it is caused by the old version of pdbfixer. You should re-install it by `conda install`.
