### ISSUE TITLE
Setting problem in complex phase during absolute binding energy calculation

### ISSUE THREAD

**Issue by Byun-jinyoung** [choderalab/yank#1243]
When I run the absolute calculation protocol, I got the error below
```
2020-10-08 17:02:21,896: Setting CUDA platform to use precision model 'double'.
2020-10-08 17:02:21,992: WARNING - openmmtools.multistate.multistatesampler - Warning: The openmmtools.multistate API is experimental and may change in future\
 releases
2020-10-08 17:02:21,992: WARNING - openmmtools.multistate.multistatesampler - Warning: The openmmtools.multistate API is experimental and may change in future\
 releases
2020-10-08 17:02:22,019: Node 1/2: executing <function ExperimentBuilder._check_resume at 0x7f8d9a3da200>
2020-10-08 17:02:22,023: Node 1/2: waiting for barrier after <function ExperimentBuilder._check_resume at 0x7f8d9a3da200>
2020-10-08 17:02:22,027: Node 1/2: waiting for barrier after _setup_molecules
2020-10-08 17:02:22,027: Group 1/2 Node 1/1: execute get_system(Tubulin-P23D03 complex)
2020-10-08 17:02:22,028: Setting up the systems for Tubulin and LIG using solvent pme
2020-10-08 17:02:22,028: Setting up solvent phase
2020-10-08 17:02:22,633: Setting up complex phase
Traceback (most recent call last):
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 357, in exec_tasks
    results.append(task(distributed_arg, *other_args, **kwargs))
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/pipeline.py", line 1349, in get_system
    ligand_id)
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/pipeline.py", line 1939, in _setup_system
    warnings = tleap.run()
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/utils.py", line 1702, in run
    leap_output = subprocess.check_output(['tleap', '-f', 'leap.in']).decode()
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tleap', '-f', 'leap.in']' returned non-zero exit status 31.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/juyong/anaconda3/envs/yank/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/experiment.py", line 737, in run_experiments
    self._setup_experiments()
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/experiment.py", line 2325, in _setup_experiments
    self._db.setup_all_systems()
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/yank/pipeline.py", line 1397, in setup_all_systems
    send_results_to=None, group_size=1, sync_nodes=True)
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 531, in distribute
    *other_args, **kwargs)
  File "/home/juyong/anaconda3/envs/yank/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 360, in exec_tasks
    error = type(e)('{}: {}'.format(node_name, str(e)))
TypeError: __init__() missing 1 required positional argument: 'cmd'
```
I think that the subprocess error related to the tleap might be from the amber tleap.
But when I uesd the tleap directly, there was no problem....

Could you tell me what I am missing... Thank you:)

**Comment by Byun-jinyoung** [comment]
I generated the .frcmod files from the amber antechamber and parmchk2

**Comment by andrrizzi** [comment]
Hi @Byun-jinyoung . Yes, that looks like a leap error. Which leap command and script are you using to try to reproduce the error? Is the leap script you are testing similar to what you (should) find in the system folder?

**Comment by giaguaro** [comment]
Was this issue resolved? I am encountering the same error as @Byun-jinyoung
