### ISSUE TITLE
Cannot find counterions for region {}

### ISSUE THREAD

**Issue by AbdulBasitAzamiAnsari** [choderalab/yank#1251]
Hi, 
I am trying to calculate the hydration-free energy of calcium ions. While running YANk I got the following error.

**ValueError: Cannot find counterions for region {}. The region has no atoms**.

There was also a warning.
**"Cannot find ligand specification. Alchemically modifying the whole solute"**. Although I provided the necessary files which are attached here.
[Simulation Yank.zip](https://github.com/choderalab/yank/files/6205854/Simulation.Yank.zip)

**Below is my input yaml file:**

options:
  minimize: yes
  verbose: yes
  output_dir: explicit
  default_number_of_iterations: 2000
  temperature: 300*kelvin
  pressure: 1*atmosphere
  resume_simulation: yes

molecules:
  Calcium:
    filepath: lig.mol2
    leap:
       parameters: [ ca.lib, ca.frcmod]

solvents:
  water:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 16*angstroms
    positive_ion: Na+
    negative_ion: Cl-
  vacuum:
    nonbonded_method: NoCutoff

systems:
  hydration-system:
    solute: Calcium
    solvent1: water
    solvent2: vacuum
    leap:
      parameters: [ leaprc.protein.ff14SB, leaprc.water.tip4pew,  ca.lib, ca.frcmod]

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]

experiments:
  system: hydration-system
  protocol: hydration-protocol

How can I fix this problem? Can anybody mention, what I missed here?

**Comment by andrrizzi** [comment]
Could you add the full Python traceback of the error? The attached log files don't have it unfortunately.

That error is incomplete as the region name is not plugged in the string in `pipeline.py:find_alchemical_counterions()` unfortunately.

**Comment by AbdulBasitAzamiAnsari** [comment]
Thank you, Sir, for your reply.
Here is the full error

Traceback (most recent call last):
  File "/home/basit/anaconda3/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/home/basit/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 751, in run_experiments
    completed[exp_index] = self._run_experiment(exp, write_status=write_status)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 3247, in _run_experiment
    built_experiment = self._build_experiment(experiment_path, experiment)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 3137, in _build_experiment
    phase_protocol)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/yank/yank.py", line 1352, in _build_default_alchemical_region
    broadcast_result=True)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/basit/anaconda3/lib/python3.7/site-packages/yank/pipeline.py", line 274, in find_alchemical_counterions
    raise ValueError("Cannot find counterions for region {}. "
ValueError: Cannot find counterions for region {}. The region has no atoms.

**Comment by andrrizzi** [comment]
It seems to me that the problem is that YANK think the Calcium solute is part of the solvent because its residue name is recognized by MDTraj as such (see names [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/residue_names.py#L23)).

Try to use the `solvent_dsl` keyword inside the `hydration-system` section to tell YANK exactly what is the atom to modify (see also the [docs](http://getyank.org/latest/yamlpages/systems.html#arbitrary-phase-free-energies-setup-by-user)).

The automatic pipeline should be able to recognize this case anyway so I'm flagging this as a bug.

**Comment by jeff231li** [comment]
@andrrizzi can Yank calculate HFE of ions or charged molecules? The code in `pipeline.find_alchemical_counterions` looks like it forces neutrality by finding a counterion.

**Comment by AbdulBasitAzamiAnsari** [comment]
Sir

I again got error while using Yank. The full error is as follows



Traceback (most recent call last):
  File "/home/scis/anaconda3/bin/yank", line 33, in <module>
    sys.exit(load_entry_point('yank==0.25.3', 'console_scripts', 'yank')())
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 738, in run_experiments
    self._generate_experiments_protocols()
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 2373, in _generate_experiments_protocols
    send_results_to=None, group_size=1, sync_nodes=True)
  File "/home/scis/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 512, in distribute
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/scis/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 512, in <listcomp>
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 2417, in _generate_experiment_protocol
    use_dummy_protocol=True)
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 3110, in _build_experiment
    gromacs_include_dir=gromacs_include_dir)
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/pipeline.py", line 469, in read_system_files
    system = create_system(parameters_file, box_vectors, create_system_args, system_options)
  File "/home/scis/anaconda3/lib/python3.7/site-packages/yank/pipeline.py", line 369, in create_system
    for key, value in system_options.items()}
AttributeError: 'NoneType' object has no attribute 'items'


My input file is 

options:
  minimize: yes
  verbose: yes
  output_dir: hydration-out
  default_number_of_iterations: 2000
  temperature: 300*kelvin
  pressure: 1*atmosphere
  resume_simulation: yes


systems:
  hydration-system:
    phase1_path: [solvent1.inpcrd, solvent1.prmtop]
    phase2_path: [solvent2.inpcrd, solvent2.prmtop]
    solvent_dsl: resname WAT
    ligand_dsl: resname Ca2+
    leap:
      parameters: [leaprc.ff14SB, leaprc.water.tip4pew, ca.lib, ca.frcmod]


protocols:
  hydration-protocol:
    solvent1:
      alchemical_path: auto
    solvent2:
      alchemical_path: auto

experiments:
  system: hydration-system
  protocol: hydration-protocol


I am attching my files.


[Simulation Yank.zip](https://github.com/choderalab/yank/files/6291659/Simulation.Yank.zip)

**Comment by andrrizzi** [comment]
> @andrrizzi can Yank calculate HFE of ions or charged molecules? The code in pipeline.find_alchemical_counterions looks like it forces neutrality by finding a counterion.

Yes, it is supported. The neutrality is enforced to make PME working, but  the hydration free energy of ions is still valid in a neutral box.

**Comment by andrrizzi** [comment]
@AbdulBasitAzamiAnsari, in the `solvent_dsl`, you also need to include the counterions which are alchemically decoupled to maintain the neutrality of the box. It looks your current selection only include water.

**Comment by AbdulBasitAzamiAnsari** [comment]
@andrrizzi , error is same even after including counterions in the solvent_dsl.

**Comment by jeff231li** [comment]
>Yes, it is supported. The neutrality is enforced to make PME working, but the hydration free energy of ions is still valid in a neutral box.

Is there an example script for running an HFE calculation for a K+ ion or something similar?

**Comment by AbdulBasitAzamiAnsari** [comment]
@andrrizzi 
When can I expect this issue to be solved?

**Comment by andrrizzi** [comment]
@AbdulBasitAzamiAnsari there is no ETA that I know of. Unfortunately, I moved to a new position in a different lab, and I use the only extra time I have to help out on the issue tracker. You are very welcome to look into the code and open PR with a fix if you have time.
