### ISSUE TITLE
yank found unknown parameter number_of_iterations in all examples. I changed nothing, just running

### ISSUE THREAD

**Issue by dxli75** [choderalab/yank#1253]
(base) root@bash#t4-lysozyme$ yank script --yaml=p-xylene-implicit.yaml 
found unknown parameter number_of_iterations
Traceback (most recent call last):
  File "/userhome/dxli-data/program/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 1191, in _validate_options
    special_conversions=special_conversions)
  File "/userhome/dxli-data/program/anaconda3/lib/python3.7/site-packages/yank/utils.py", line 1058, in validate_parameters
    raise TypeError("found unknown parameter {}".format(', '.join(diff)))
TypeError: found unknown parameter number_of_iterations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/userhome/dxli-data/program/anaconda3/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/userhome/dxli-data/program/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/userhome/dxli-data/program/anaconda3/lib/python3.7/site-packages/yank/commands/script.py", line 147, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/userhome/dxli-data/program/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 591, in __init__
    self.parse(script)
  File "/userhome/dxli-data/program/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 681, in parse
    validate_general_options=True))
  File "/userhome/dxli-data/program/anaconda3/lib/python3.7/site-packages/yank/experiment.py", line 1193, in _validate_options
    raise YamlParseError(str(e))
yank.experiment.YamlParseError: found unknown parameter number_of_iterations

**Comment by jchodera** [comment]
I'm afraid the examples have drifted out of date as the YAML syntax was revised. We're shortstaffed due to COVID, but hope to have more folks coming aboard to remediate this in the next couple of months.

**Comment by dxli75** [comment]
Thanks
