### ISSUE TITLE
yank-example-hydration-phenol-Analysis-error

### ISSUE THREAD

**Issue by owenustc** [choderalab/yank#1264]
Hi, I run example of yank, run-explicit.sh, and meet the error as follow, and my Yank Version is 0.25.2. mbar is 3.0.5.dev-Unknown, openmm is 7.6.0.dev-ad113a0.  
dcdplugin) Could not access file 'explicit/experiments/trailblaze/solvent1/coordinates.dcd'.
dcdplugin) Could not access file 'explicit/experiments/trailblaze/solvent2/coordinates.dcd'.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 403, in __get__
    value = instance._cache[self.name]
KeyError: 'mbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.9/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/experiment.py", line 751, in run_experiments
    completed[exp_index] = self._run_experiment(exp, write_status=write_status)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/experiment.py", line 3251, in _run_experiment
    built_experiment.run(n_iterations=switch_experiment_interval)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/experiment.py", line 427, in run
    alchemical_phase.run(n_iterations=iterations_to_run)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/yank.py", line 1207, in run
    self._sampler.run(n_iterations=n_iterations)
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistatesampler.py", line 690, in run
    self._update_analysis()
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistatesampler.py", line 1553, in _update_analysis
    self._last_err_free_energy = self._offline_analysis()
  File "/root/miniconda3/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 621, in _delayed_termination
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/utils.py", line 87, in _wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistatesampler.py", line 1428, in _offline_analysis
    mbar = analysis.mbar
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 405, in __get__
    value = self._get_default(instance)
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 426, in _get_default
    value = self._default(self, instance)
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 2130, in mbar
    return instance._create_mbar(instance._unbiased_decorrelated_u_ln,
  File "/root/miniconda3/lib/python3.9/site-packages/openmmtools/multistate/multistateanalyzer.py", line 1041, in _create_mbar
    self.mbar = MBAR(energy_matrix, samples_per_state, **self._extra_analysis_kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/pymbar/mbar.py", line 304, in __init__
    self.f_k = mbar_solvers.solve_mbar_for_all_states(self.u_kn, self.N_k, self.f_k, solver_protocol)
  File "/root/miniconda3/lib/python3.9/site-packages/pymbar/mbar_solvers.py", line 547, in solve_mbar_for_all_states
    f_k_nonzero, all_results = solve_mbar(u_kn[states_with_samples], N_k[states_with_samples],
  File "/root/miniconda3/lib/python3.9/site-packages/pymbar/mbar_solvers.py", line 515, in solve_mbar
    f_k_nonzero, results = solve_mbar_once(u_kn_nonzero, N_k_nonzero, f_k_nonzero, **options)
  File "/root/miniconda3/lib/python3.9/site-packages/pymbar/mbar_solvers.py", line 444, in solve_mbar_once
    results = adaptive(u_kn_nonzero, N_k_nonzero, f_k_nonzero, tol=tol, options=options)
  File "/root/miniconda3/lib/python3.9/site-packages/pymbar/mbar_solvers.py", line 293, in adaptive
    Hinvg = np.linalg.lstsq(H, g, rcond=-1)[0]
  File "<__array_function__ internals>", line 5, in lstsq
  File "/root/miniconda3/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
ValueError: On entry to DLASCL parameter number 4 had an illegal value
2022-01-25 15:10:37,626: Single node: executing <bound method MultiStateReporter.close of <openmmtools.multistate.multistatereporter.MultiStateReporter object at 0x7fb598b10eb0>>
2022-01-25 15:10:37,640: Single node: executing <bound method MultiStateReporter.close of <openmmtools.multistate.multistatereporter.MultiStateReporter object at 0x7fb5348841c0>>
Analyzing data...
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/root/miniconda3/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.9/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/root/miniconda3/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/analyze.py", line 782, in analyze_directory
    auto_experiment_analyzer = ExperimentAnalyzer(source_directory, **analyzer_kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/yank/analyze.py", line 297, in __init__
    raise RuntimeError(err_msg)
RuntimeError: Cannot find analysis.yaml script in experiments
Exception ignored in: <function ExperimentAnalyzer.__del__ at 0x7fa5ebca9ca0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/yank/analyze.py", line 336, in __del__
    for phase, analyzer in self.analyzers.items():
AttributeError: 'ExperimentAnalyzer' object has no attribute 'analyzers'

**Comment by lilyminium** [comment]
> File "/root/miniconda3/lib/python3.9/site-packages/yank/analyze.py", line 297, in init
raise RuntimeError(err_msg)
RuntimeError: Cannot find analysis.yaml script in experiments

I think the underlying cause of this error might be the lack of an `analysis.yaml` script, not yaml version. @owenustc do you have one?
