### ISSUE TITLE
Yank analysis error

### ISSUE THREAD

**Issue by kingljy0818** [choderalab/yank#1279]
Dear all,

When I type 'yank analyze --store=compd4-1pn9a-explicit-output/experiments', it was displayed the error in the following:

--------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anaconda3/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/home/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/home/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 782, in analyze_directory
    auto_experiment_analyzer = ExperimentAnalyzer(source_directory, **analyzer_kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 299, in __init__
    analysis = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
Exception ignored in: <function ExperimentAnalyzer.__del__ at 0x7f59e6ca79e0>
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 336, in __del__
    for phase, analyzer in self.analyzers.items():
AttributeError: 'ExperimentAnalyzer' object has no attribute 'analyzers'

-------------------------------------------------------------------------------------------------------------------------

I also checked the pymbar version was 3.0.3, would need your help to solve this problem. Many thanks.

Jiyuan

**Comment by andrrizzi** [comment]
This is due to an update in PyYAML (see also #1265). A fix by @mikemhenry (conda-forge/yank-feedstock#3) should be soon available. For now you should be able to revert pyyaml to < 6 to fix the issue.

**Comment by kingljy0818** [comment]
Thanks, Andrrizzi. I have downgraded pyyaml 6.0 to 5.4.1, but I also got the error in the following:

--------------------------------------------------------------------------------------------------------------------
(base) [root@localhost ~]# yank analyze --store=compd4-1pn9a-explicit-output/experiments
Traceback (most recent call last):
  File "/home/anaconda3/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/home/anaconda3/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/commands/analyze.py", line 148, in dispatch
    single_run()
  File "/home/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/commands/analyze.py", line 143, in single_run
    output = analyze.analyze_directory(args['--store'], **analyzer_kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 782, in analyze_directory
    auto_experiment_analyzer = ExperimentAnalyzer(source_directory, **analyzer_kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 297, in __init__
    raise RuntimeError(err_msg)
RuntimeError: Cannot find analysis.yaml script in compd4-1pn9a-explicit-output/experiments
Exception ignored in: <function ExperimentAnalyzer.__del__ at 0x7f465562bb90>
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 336, in __del__
    for phase, analyzer in self.analyzers.items():
AttributeError: 'ExperimentAnalyzer' object has no attribute 'analyzers'

------------------------------------------------------------------------------------------------------------------------------

Would you have a look and give me some suggestions to solve this problem.

**Comment by andrrizzi** [comment]
Hi @kingljy0818 . This might have something to do with choderalab/openmmtools#555 . If your simulation did save at least 1 iteration, my first guess, is that you generated the simulation using openmmtools < 0.21.3 and it got upgraded when downgrading YAML.

**Comment by andrrizzi** [comment]
You need version < 0.21.3 so at least 0.21.2. Ideally, the same you used to generate the data. If you did generate the simulation data with 0.21.4 then I'd suggest you open an issue on openmmtools as well (linking to this one) as it might be something introduced with that version.

**Comment by kingljy0818** [comment]
Due to I downgraded the openmmtools to 21.3, I redid the yank task, after the calculation completed, the yank analyze could be normal, the result displayed in the following:

----------------------------------------------------------------------------------------------------------------------------------
(base) [root@localhost t4-lysozyme]# yank analyze --store=compd4-1pn9a-explicit-output/experiments
/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py:299: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  analysis = yaml.load(f)
2022-06-29 12:07:43,273: WARNING - openmmtools.multistate.multistatereporter - Warning: The openmmtools.multistate API is experimental and may change in future releases
2022-06-29 12:07:43,312: WARNING - openmmtools.multistate.multistateanalyzer - Warning: The openmmtools.multistate API is experimental and may change in future releases
2022-06-29 12:07:43,315: WARNING - openmmtools.multistate.multistatereporter - Warning: The openmmtools.multistate API is experimental and may change in future releases
2022-06-29 12:07:43,338: WARNING - openmmtools.multistate.multistateanalyzer - Warning: The openmmtools.multistate API is experimental and may change in future releases
Free energy of binding  :   -10.026 +- 1.806 kT (-5.977 +- 1.077 kcal/mol)
DeltaG complex          :   112.667 +- 1.529 kT
DeltaG standard state correction:              0.280 kT
DeltaG solvent          :   102.921 +- 0.960 kT

Enthalpy of binding     :  -854.760 +- 62.453 kT (-509.575 +- 37.232 kcal/mol)
--------------------------------------------------------------------------------------------------------------------------------------------

The first and second line prompt "/home/anaconda3/lib/python3.7/site-packages/yank/analyze.py:299: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.", would ask you what is the reason, and What should I do to get rid of this prompt？

**Comment by andrrizzi** [comment]
That's a developer warning. Nothing to worry about. Seems like the issue was resolved. Feel free to re-open if necessary.
