### ISSUE TITLE
Cannot apply the restraint. No receptor-ligand complex could be found.

### ISSUE THREAD

**Issue by JacekKedzierski** [choderalab/yank#1281]
Hello, I have just started using Yank to do the prediction of absolute free energy. The tutorial for T4 lysosome with a small probe went smoothly however since I am now trying to use my example the script crashes. It seems that the receptor-ligand complex is missing but it is ready in setup/systems/MNK1-DS/complex.pdb. Could you please help me with this error?

Traceback (most recent call last):
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/bin/yank", line 10, in <module>
    sys.exit(main())
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/experiment.py", line 751, in run_experiments
    completed[exp_index] = self._run_experiment(exp, write_status=write_status)
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/experiment.py", line 3251, in _run_experiment
    built_experiment.run(n_iterations=switch_experiment_interval)
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/experiment.py", line 402, in run
    alchemical_phase = phase.initialize_alchemical_phase()
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/experiment.py", line 268, in initialize_alchemical_phase
    alchemical_phase = self.create_alchemical_phase()
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/experiment.py", line 253, in create_alchemical_phase
    alchemical_phase.create(anisotropic_dispersion_cutoff=dispersion_cutoff,
  File "/mnt/jacek/jkedzierski/Documents/Install/miniconda3/envs/MNK1_Yank/lib/python3.8/site-packages/yank/yank.py", line 987, in create
    raise RuntimeError("Cannot apply the restraint. No receptor-ligand "
RuntimeError: Cannot apply the restraint. No receptor-ligand complex could be found.

**Comment by giaguaro** [comment]
Maybe try to fix the ligand prior to the run?
