### ISSUE TITLE
I got the following error.

### ISSUE THREAD

**Issue by VirtualChemist** [choderalab/yank#1295]
Hi,
When i tried to the yank-example file. I got the following error.

2023-03-17 15:28:45,037: Running _compute_replica_energies serially.
Traceback (most recent call last):
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/cache.py", line 445, in get_context
    context = self._lru[context_id]
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/cache.py", line 147, in __getitem__
    entry = self._data.pop(key)
KeyError: (8749923509185095026, -2790907321978132361)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/medicina/anaconda3/envs/fep/bin/yank", line 11, in <module>
    load_entry_point('yank==0.25.2', 'console_scripts', 'yank')()
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/commands/script.py", line 155, in dispatch
    yaml_builder.run_experiments(write_status=write_status)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/experiment.py", line 751, in run_experiments
    completed[exp_index] = self._run_experiment(exp, write_status=write_status)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/experiment.py", line 3251, in _run_experiment
    built_experiment.run(n_iterations=switch_experiment_interval)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/experiment.py", line 427, in run
    alchemical_phase.run(n_iterations=iterations_to_run)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/yank.py", line 1207, in run
    self._sampler.run(n_iterations=n_iterations)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 652, in run
    raise e
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 642, in run
    self._compute_energies()
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/utils.py", line 87, in _wrapper
    return func(*args, **kwargs)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 1319, in _compute_energies
    send_results_to=0)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 512, in distribute
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 512, in <listcomp>
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 1351, in _compute_replica_energies
    context, integrator = cache.global_context_cache.get_context(compatible_group[0])
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/cache.py", line 447, in get_context
    context = thermodynamic_state.create_context(integrator, self._platform, self._platform_properties)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/states.py", line 1174, in create_context
    return openmm.Context(system, integrator, platform)
  File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture'

Can anyone tell how to fix this issue.
I have install the package using "conda install -c omnia yank"
I am using Yank=0.25.2 version.
My CUDA version is 11.4.

Thanks

**Comment by mikemhenry** [comment]
We do not have the personal/funding to maintain yank as well as we would like to. It looks like openmm is having a hard time making a context on your GPU, what version of openmm do you have installed?

**Comment by VirtualChemist** [comment]
Thank you for your quick response.

The openmm package version is 7.4.2.

**Comment by smutao** [comment]
> Hi, When i tried to the yank-example file. I got the following error.
> 
> 2023-03-17 15:28:45,037: Running _compute_replica_energies serially. Traceback (most recent call last): File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/cache.py", line 445, in get_context context = self._lru[context_id] File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/cache.py", line 147, in **getitem** entry = self._data.pop(key) KeyError: (8749923509185095026, -2790907321978132361)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/medicina/anaconda3/envs/fep/bin/yank", line 11, in load_entry_point('yank==0.25.2', 'console_scripts', 'yank')() File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/cli.py", line 73, in main dispatched = getattr(commands, command).dispatch(command_args) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/commands/script.py", line 155, in dispatch yaml_builder.run_experiments(write_status=write_status) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/experiment.py", line 751, in run_experiments completed[exp_index] = self._run_experiment(exp, write_status=write_status) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/experiment.py", line 3251, in _run_experiment built_experiment.run(n_iterations=switch_experiment_interval) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/experiment.py", line 427, in run alchemical_phase.run(n_iterations=iterations_to_run) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/yank/yank.py", line 1207, in run self._sampler.run(n_iterations=n_iterations) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 652, in run raise e File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 642, in run self._compute_energies() File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/utils.py", line 87, in _wrapper return func(*args, **kwargs) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 1319, in _compute_energies send_results_to=0) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 512, in distribute all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args] File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/mpiplus/mpiplus.py", line 512, in all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args] File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/multistate/multistatesampler.py", line 1351, in _compute_replica_energies context, integrator = cache.global_context_cache.get_context(compatible_group[0]) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/cache.py", line 447, in get_context context = thermodynamic_state.create_context(integrator, self._platform, self._platform_properties) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/openmmtools/states.py", line 1174, in create_context return openmm.Context(system, integrator, platform) File "/home/medicina/anaconda3/envs/fep/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in **init** this = _openmm.new_Context(*args) Exception: Error launching CUDA compiler: 256 nvcc fatal : Value 'sm_86' is not defined for option 'gpu-architecture'
> 
> Can anyone tell how to fix this issue. I have install the package using "conda install -c omnia yank" I am using Yank=0.25.2 version. My CUDA version is 11.4.
> 
> Thanks

Did you install cudatoolkit via conda or outside conda?

**Comment by VirtualChemist** [comment]
Thanks for your reply.
I have installed the cudatoolkit outside of conda.
Should I install cudatoolkit inside the conda for yank envs.

Thanks

**Comment by smutao** [comment]
> Thanks for your reply. I have installed the cudatoolkit outside of conda. Should I install cudatoolkit inside the conda for yank envs.
> 
> Thanks

If you follow installation instruction of YANK via conda, cudatoolkit will be installed at the same time.

**Comment by VirtualChemist** [comment]
Unfortunately, I installed the YANK package via conda.
If you check my previous message in this tread. I installed the YANK using this command 
"conda install -c omnia yank"

Also, when i check the cudatoolkit package inside the YANK envs, result was none. It means the YANK package didn't install the cudatoolkit by default.
