### ISSUE TITLE
Return more helpful error message when no ligand atoms specified 

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/yank#308]
```
inpcrd: setup/complex.inpcrd
TOTAL ATOMS      :      2831
receptor         :      2831
ligand           :         0
phases: ['complex-implicit', 'solvent-implicit']
systems: ['complex-implicit', 'solvent-implicit']
positions: ['complex-implicit', 'solvent-implicit']
atom_indices: ['complex-implicit', 'solvent-implicit']
thermodynamic_state: <ThermodynamicState object, temperature = 300 K, pressure = 1 atm>
Creating receptor-ligand restraints...
Traceback (most recent call last):
  File "/cbio/jclab/home/albaness/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 102, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/prepare.py", line 39, in dispatch
    return dispatch_binding(args)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/prepare.py", line 476, in dispatch_binding
    yank.create(phases, systems, positions, atom_indices, thermodynamic_state, options=options)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 197, in create
    self._create_phase(phase, systems[phase], positions[phase], atom_indices[phase], thermodynamic_state, protocols=protocols, options=options, mpicomm=mpicomm)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 287, in _create_phase
    restraints = HarmonicReceptorLigandRestraint(thermodynamic_state, reference_system, reference_positions, atom_indices['receptor'], atom_indices['ligand'])
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/restraints.py", line 97, in __init__
    self.restrained_ligand_atom = self._closestAtomToCentroid(self.coordinates, self.ligand_atoms)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/restraints.py", line 377, in _closestAtomToCentroid
    closest_atom = int(np.argmin(distances))
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 960, in argmin
    return argmin(axis)
ValueError: attempt to get argmin of an empty sequence
```
This is the current error message

**Comment by andrrizzi** [comment]
Oh! Just seen this. Related to #380 and #383. It's been resolved in PR #389. Closing this one.
