### ISSUE TITLE
Failure with yank host-guest-implicit example in conda-installed package

### ISSUE THREAD

**Issue by leelasd** [choderalab/yank#321]
This failure occurred while running `host-guest-implicit` for conda-installed YANK with conda-installed OpenMM 6.3:
```
Creating and caching Context objects...
Creating Context for state 0...
Traceback (most recent call last):
  File "/Users/Sriram/anaconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/cli.py", line 98, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/commands/run.py", line 61, in dispatch
    yank.run(mpicomm, options=options)
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/yank.py", line 406, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/repex.py", line 942, in run
    self._initialize_resume()
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-macosx-10.5-x86_64.egg/yank/repex.py", line 1223, in _initialize_resume
    state._integrator = self.mm.LangevinIntegrator(state.temperature, self.collision_rate, self.timestep)
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 11922, in __init__
    this = _openmm.new_LangevinIntegrator(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_LangevinIntegrator'.
  Possible C/C++ prototypes are:
    OpenMM::LangevinIntegrator::LangevinIntegrator(double,double,double)
    OpenMM::LangevinIntegrator::LangevinIntegrator(OpenMM::LangevinIntegrator const &)
```

**Comment by leelasd** [comment]
Installing from git head also ran into a weird issue:
```
vpn172022162135:yank Sriram$ git clone https://github.com/choderalab/yank.git
Cloning into 'yank'...
remote: Counting objects: 4410, done.
^RReceiving objects:  22% (971/4410), 620.01 KiB | 404.00 KiB/s     
yankReceiving objects:  22% (990/4410), 1.50 MiB | 370.00 KiB/s       
nstall Receiving objects:  22% (991/4410), 2.25 MiB | 270.00 KiB/s     
remote: Total 4410 (delta 0), reused 0 (delta 0), pack-reused 4410
Receiving objects: 100% (4410/4410), 34.23 MiB | 137.00 KiB/s, done.
Resolving deltas: 100% (2869/2869), done.
Checking connectivity... done.
vpn172022162135:yank Sriram$ cd yank
vpn172022162135:yank Sriram$ python setup.py install 
Compiling ./Yank/mixing/_mix_replicas.pyx because it changed.
[1/1] Cythonizing ./Yank/mixing/_mix_replicas.pyx
/Users/Sriram/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/Users/Sriram/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/Users/Sriram/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib.macosx-10.5-x86_64-2.7
creating build/lib.macosx-10.5-x86_64-2.7/yank
```

**Comment by andrrizzi** [comment]
Confirmed with conda installation but not head version.

I got the same error after a fresh conda install (which updated Yank's dependencies). I couldn't reproduce the compilation warnings you obtained though. The example works for me with the git head version. Does the head version works for you?

**Comment by andrrizzi** [comment]
I can't reproduce this anymore with the new yank release, so I'm assuming the OpenMM problem is gone with the new version. Feel free to reopen this if it's not.
