### ISSUE TITLE
Cluster MPI run issues

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#346]
When I installed `yank-dev` via anaconda cloud, I ran into a `glibc` incompatibility issue:
```
Iteration 2 / 200
2016-02-24 14:16:44,345: Mixing replicas...
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
    yaml_builder.build_experiment()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1203, in build_experiment
    self._run_experiment(combination, output_dir)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1778, in _run_experiment
    yank.run()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 451, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 840, in run
    self._mix_replicas()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1559, in _mix_replicas
    self._mix_all_replicas_cython()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1474, in _mix_all_replicas_cython
    from mixing._mix_replicas import _mix_replicas_cython
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/mixing/_mix_replicas.so)
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
    yaml_builder.build_experiment()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1203, in build_experiment
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
    yaml_builder.build_experiment()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1203, in build_experiment
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
    yaml_builder.build_experiment()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1203, in build_experiment
    yaml_builder.build_experiment()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1203, in build_experiment
    self._run_experiment(combination, output_dir)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1778, in _run_experiment
    self._run_experiment(combination, output_dir)
    self._run_experiment(combination, output_dir)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1778, in _run_experiment
    self._run_experiment(combination, output_dir)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1778, in _run_experiment
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1778, in _run_experiment
    yank.run()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 451, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 840, in run
    yank.run()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 451, in run
    yank.run()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 451, in run
    yank.run()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 451, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 843, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 843, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 843, in run
    self._mix_replicas()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1543, in _mix_replicas
    self._propagate_replicas()
    self._propagate_replicas()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/sampling.py", line 656, in _propagate_replicas
    self._propagate_replicas()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/sampling.py", line 656, in _propagate_replicas
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/sampling.py", line 656, in _propagate_replicas
    ReplicaExchange._propagate_replicas(self)
    ReplicaExchange._propagate_replicas(self)
    ReplicaExchange._propagate_replicas(self)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1288, in _propagate_replicas
    self.replica_states = self.mpicomm.bcast(self.replica_states, root=0)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1288, in _propagate_replicas
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1288, in _propagate_replicas
  File "MPI/Comm.pyx", line 1276, in mpi4py.MPI.Comm.bcast (src/mpi4py.MPI.c:108819)
    self._propagate_replicas_mpi()
    self._propagate_replicas_mpi()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1231, in _propagate_replicas_mpi
    self._propagate_replicas_mpi()
  File "MPI/msgpickle.pxi", line 613, in mpi4py.MPI.PyMPI_bcast (src/mpi4py.MPI.c:47032)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1231, in _propagate_replicas_mpi
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1231, in _propagate_replicas_mpi
mpi4py.MPI.Exception    replica_lookup = dict( (self.replica_states[replica_index], replica_index) for replica_index in range(self.nstates) ) # replica_lookup[state_index] is the replica index currently at state 'state_index' # Python 2.6 compatible
    replica_lookup = dict( (self.replica_states[replica_index], replica_index) for replica_index in range(self.nstates) ) # replica_lookup[state_index] is the replica index currently at state 'state_index' # Python 2.6 compatible
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1231, in <genexpr>
    replica_lookup = dict( (self.replica_states[replica_index], replica_index) for replica_index in range(self.nstates) ) # replica_lookup[state_index] is the replica index currently at state 'state_index' # Python 2.6 compatible
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1231, in <genexpr>
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1231, in <genexpr>
    replica_lookup = dict( (self.replica_states[replica_index], replica_index) for replica_index in range(self.nstates) ) # replica_lookup[state_index] is the replica index currently at state 'state_index' # Python 2.6 compatible
    replica_lookup = dict( (self.replica_states[replica_index], replica_index) for replica_index in range(self.nstates) ) # replica_lookup[state_index] is the replica index currently at state 'state_index' # Python 2.6 compatible
TypeError:     replica_lookup = dict( (self.replica_states[replica_index], replica_index) for replica_index in range(self.nstates) ) # replica_lookup[state_index] is the replica index currently at state 'state_index' # Python 2.6 compatible
'NoneType' object has no attribute '__getitem__'
TypeError: 'NoneType' object has no attribute '__getitem__'
TypeError: 'NoneType' object has no attribute '__getitem__'

=====================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
=====================================================================================
[proxy:0:1@gpu-1-13.local] HYD_pmcd_pmip_control_cmd_cb (./pm/pmiserv/pmip_cb.c:928): assert (!closed) failed
[proxy:0:1@gpu-1-13.local] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:1@gpu-1-13.local] main (./pm/pmiserv/pmip.c:226): demux engine error waiting for event
[mpiexec@gpu-1-12.local] HYDT_bscu_wait_for_completion (./tools/bootstrap/utils/bscu_wait.c:70): one of the processes terminated badly; aborting
[mpiexec@gpu-1-12.local] HYDT_bsci_wait_for_completion (./tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@gpu-1-12.local] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:191): launcher returned error waiting for completion
[mpiexec@gpu-1-12.local] main (./ui/mpich/mpiexec.c:405): process manager error waiting for completion
```
It looks like the newest travis docker build framework may be using a too-recent version of `linux`.

The easiest way to fix this might be to revert to the old precise penguin build framework by setting `sudo: true` in [`.travis.yml`](https://github.com/choderalab/yank/blob/master/.travis.yml#L2).

**Comment by hlfsimko** [comment]
I encounter the same issue. Is the recommended solution still to change the setting `sudo: true` in `.travis.yml`?

**Comment by jchodera** [comment]
We have to change this on our end so the build framework rebuilds the conda package and pushed it to anaconda cloud correctly.

Let me fix this.

Out of curiosity, what Linux distribution did you run into this problem with?

**Comment by hlfsimko** [comment]
Great thanks. Please find the distro info below.

`Distributor ID:	SUSE LINUX
Description:	SUSE Linux Enterprise Desktop 11 (x86_64)
Release:	11`
