### ISSUE TITLE
Error in Selftest:  TypeError: in method 'LangevinIntegrator_step'

### ISSUE THREAD

**Issue by coalmeister** [choderalab/yank#364]
After installation of yank, then subsequently yank-dev, I observe failure in LangevinIntegrator step when running examples and selftest:
```
[user@cchem2 abl-imatinib-explicit]$ yank selftest
Running doctests for all modules...
/home/user/anaconda2/lib/python2.7/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting Replica States dtype=int32 to <type 'numpy.int64'> 
  TypeCastPerformanceWarning)
**********************************************************************
File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 516, in yank.repex.ReplicaExchange
Failed example:
    simulation.run()
Exception raised:
    Traceback (most recent call last):
      File "/home/user/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest yank.repex.ReplicaExchange[23]>", line 1, in <module>
        simulation.run()
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 806, in run
        self._propagate_replicas()
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 1253, in _propagate_replicas
        self._propagate_replicas_serial()
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 1235, in _propagate_replicas_serial
        self._propagate_replica(replica_index)
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 1150, in _propagate_replica
        integrator.step(self.nsteps_per_iteration)
      File "/home/user/anaconda2/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4731, in step
        return _openmm.LangevinIntegrator_step(self, steps)
    TypeError: in method 'LangevinIntegrator_step', argument 2 of type 'int'
**********************************************************************
1 items had failures:
   1 of  24 in yank.repex.ReplicaExchange
***Test Failed*** 1 failures.
WARNING: There were 1 doctest failures.
[user@cchem2 abl-imatinib-explicit]$ conda install yank-dev
Fetching package metadata: ......
Solving package specifications: .........
Warning: 2 possible package resolutions (only showing differing packages):
  - pdbfixer-1.2-np19py27_1.tar.bz2
  - pdbfixer-1.2-py27_1.tar.bz2

Package plan for installation in environment /home/user/anaconda2:

The following NEW packages will be INSTALLED:

    yank-dev: 0.0.0-py27_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################################################################################################| 100%
[user@cchem2 abl-imatinib-explicit]$ yank selftest
Running doctests for all modules...
/home/user/anaconda2/lib/python2.7/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting Replica States dtype=int32 to <type 'numpy.int64'> 
  TypeCastPerformanceWarning)
**********************************************************************
File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 516, in yank.repex.ReplicaExchange
Failed example:
    simulation.run()
Exception raised:
    Traceback (most recent call last):
      File "/home/user/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest yank.repex.ReplicaExchange[23]>", line 1, in <module>
        simulation.run()
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 806, in run
        self._propagate_replicas()
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 1253, in _propagate_replicas
        self._propagate_replicas_serial()
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 1235, in _propagate_replicas_serial
        self._propagate_replica(replica_index)
      File "/home/user/anaconda2/lib/python2.7/site-packages/yank/repex.py", line 1150, in _propagate_replica
        integrator.step(self.nsteps_per_iteration)
      File "/home/user/anaconda2/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4731, in step
        return _openmm.LangevinIntegrator_step(self, steps)
    TypeError: in method 'LangevinIntegrator_step', argument 2 of type 'int'
**********************************************************************
1 items had failures:
   1 of  24 in yank.repex.ReplicaExchange
***Test Failed*** 1 failures.
WARNING: There were 1 doctest failures.
```

**Comment by jchodera** [comment]
Make sure you don't have `yank` and `yank-dev` installed simultaneously. I think this issue was fixed [some time ago](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L2041-L2042), with the fix involving [casting NetCDF integers to Python integers](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L2041-L2042), but your installation of both `yank` and `yank-dev` appears to fail at exactly the same line, suggesting the bugfixes weren't brought in with the newer `yank-dev`.

We don't yet have a way of automatically ensuring we uninstall one before installing the other.  You can ensure only `yank-dev` is installed with:
```bash
conda remove --yes yank yank-dev
conda clean -pltis --yes
conda install --yes yank-dev
```

The latest `yank-dev` passes these self-tests on our machines:
```
yank selftest[chodera@gpu-1-8 ~]$ yank selftest
Running doctests for all modules...
/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting Replica States dtype=int32 to <type 'numpy.int64'> 
  TypeCastPerformanceWarning)
2016-04-14 17:18:41,481: Setting up the system for T4lysozyme, vacuum and p-xylene
2016-04-14 17:18:46,680: WARNING - yank.yamlbuild - Changing starting ligand positions.
All doctests pass.
```

**Comment by spadavec** [comment]
I'm seeing (what I believe) the same issue: 

**
$ yank selftest
**
Running doctests for all modules...
/Users/xxxx/anaconda/lib/python2.7/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting Replica States dtype=int32 to <type 'numpy.int64'> 
  TypeCastPerformanceWarning)
**********************************************************************
File "/Users/xxxx/anaconda/lib/python2.7/site-packages/yank/repex.py", line 516, in yank.repex.ReplicaExchange
Failed example:
    simulation.run()
Exception raised:
    Traceback (most recent call last):
      File "/Users/xxxx/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest yank.repex.ReplicaExchange[23]>", line 1, in <module>
        simulation.run()
      File "/Users/xxxx/anaconda/lib/python2.7/site-packages/yank/repex.py", line 806, in run
        self._propagate_replicas()
      File "/Users/xxxx/anaconda/lib/python2.7/site-packages/yank/repex.py", line 1253, in _propagate_replicas
        self._propagate_replicas_serial()
      File "/Users/xxxx/anaconda/lib/python2.7/site-packages/yank/repex.py", line 1235, in _propagate_replicas_serial
        self._propagate_replica(replica_index)
      File "/Users/xxxx/anaconda/lib/python2.7/site-packages/yank/repex.py", line 1150, in _propagate_replica
        integrator.step(self.nsteps_per_iteration)
      File "/Users/xxxx/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 13564, in step
        return _openmm.LangevinIntegrator_step(self, steps)
    TypeError: in method 'LangevinIntegrator_step', argument 2 of type 'int'
**********************************************************************
1 items had failures:
   1 of  24 in yank.repex.ReplicaExchange
***Test Failed*** 1 failures.
WARNING: There were 1 doctest failures.

I should only have the Release version installed, which was installed via: 

**
$ conda install -c https://conda.binstar.org/omnia yank
**
(after Anaconda was installed) on a OSX-64 machine.

**Comment by jchodera** [comment]
That error was fixed some time ago, but I don't think we've cut a new prerelease version since then. I'll see if we can do that now. Thanks for bringing that to our attention!

**Comment by jchodera** [comment]
New prerelease is out!  Let us know if you still have this issue after upgrading or starting from a clean install!
