### ISSUE TITLE
MPI errors when running on more than 8 GPUs

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/yank#367]
Just wanted to raise this issue because I think @andrrizzi has seen it as well. I get the following error whenever I try to run a YANK simulation in MPI mode on more than 8 GPUS: 

```
gpu-3-8-gpu3
gpu-3-8-gpu2
gpu-3-8-gpu1
gpu-3-8-gpu0
gpu-1-10-gpu3
gpu-1-10-gpu2
gpu-1-10-gpu1
gpu-1-10-gpu0
gpu-2-11-gpu3
gpu-2-11-gpu2
gpu-2-11-gpu1
gpu-2-11-gpu0
gpu-1-13-gpu3
gpu-1-13-gpu2
gpu-1-13-gpu1
gpu-1-13-gpu0
gpu-1-17-gpu3
gpu-1-17-gpu2
gpu-1-17-gpu1
gpu-1-17-gpu0
Running simulation via MPI...
[mpiexec@gpu-3-8.local] match_arg (./utils/args/args.c:122): unrecognized argument 
[mpiexec@gpu-3-8.local] HYDU_parse_array (./utils/args/args.c:140): argument matching returned error
[mpiexec@gpu-3-8.local] parse_args (./ui/mpich/utils.c:1387): error parsing input array
[mpiexec@gpu-3-8.local] HYD_uii_mpx_get_parameters (./ui/mpich/utils.c:1475): error parsing config args

Usage: ./mpiexec [global opts] [exec1 local opts] : [exec2 local opts] : ...

Global options (passed to all executables):

  Global environment options:
    -genv {name} {value}             environment variable name and value
    -genvlist {env1,env2,...}        environment variable list to pass
    -genvnone                        do not pass any environment variables
    -genvall                         pass all environment variables not managed
                                          by the launcher (default)

  Other global options:
    -f {name}                        file containing the host names
    -hosts {host list}               comma separated host list
    -wdir {dirname}                  working directory to use
    -configfile {name}               config file containing MPMD launch options


Local options (passed to individual executables):

  Local environment options:
    -env {name} {value}              environment variable name and value
    -envlist {env1,env2,...}         environment variable list to pass
    -envnone                         do not pass any environment variables
    -envall                          pass all environment variables (default)

  Other local options:
    -n/-np {value}                   number of processes
    {exec_name} {args}               executable name and arguments


Hydra specific options (treated as global):

  Launch options:
    -launcher                        launcher to use ( ssh rsh fork slurm ll lsf sge manual persist)
    -launcher-exec                   executable to use to launch processes
    -enable-x/-disable-x             enable or disable X forwarding

  Resource management kernel options:
    -rmk                             resource management kernel to use ( user slurm ll lsf sge pbs)

  Hybrid programming options:
    -ranks-per-proc                  assign so many ranks to each process

  Processor topology options:
    -binding                         process-to-core binding mode
    -topolib                         processor topology library ( hwloc plpa)

  Checkpoint/Restart options:
    -ckpoint-interval                checkpoint interval
    -ckpoint-prefix                  checkpoint file prefix
    -ckpoint-num                     checkpoint number to restart
    -ckpointlib                      checkpointing library (none)

  Demux engine options:
    -demux                           demux engine ( poll select)

  Other Hydra options:
    -verbose                         verbose mode
    -info                            build information
    -print-all-exitcodes             print exit codes of all processes
    -iface                           network interface to use
    -ppn                             processes per node
    -profile                         turn on internal profiling
    -prepend-rank                    prepend rank to output
    -prepend-pattern                 prepend pattern to output
    -outfile-pattern                 direct stdout to file
    -errfile-pattern                 direct stderr to file
    -nameserver                      name server information (host:port format)
    -disable-auto-cleanup            don't cleanup processes on error
    -disable-hostname-propagation    let MPICH2 auto-detect the hostname
    -order-nodes                     order nodes as ascending/descending cores

Please see the intructions provided at
http://wiki.mcs.anl.gov/mpich2/index.php/Using_the_Hydra_Process_Manager
for further details

Thu Apr 21 11:03:00 EDT 2016
Set compute mode to DEFAULT for GPU 0000:84:00.0.
All done.
Set compute mode to DEFAULT for GPU 0000:83:00.0.
All done.
Set compute mode to DEFAULT for GPU 0000:04:00.0.
All done.
Set compute mode to DEFAULT for GPU 0000:03:00.0.
All done.

```

**Comment by jchodera** [comment]
Can you paste the `configfile` that was generated by `build_mpi_runfile`?

**Comment by andrrizzi** [comment]
I actually had something different. When trying to run on more than 8 GPUs I just got the `yank help` output.

**Comment by jchodera** [comment]
`build_mpirun_configfile` currently puts everything on one line.  I suspect what is happening is that some line limit is truncating what is actually processed, so that when the line grows longer than a certain length, part of the command is truncated and you end up with weird error messages.

The `configfile` *should* be able to span multiple lines:
http://linuxcommand.org/man_pages/mpiexec1.html

I think we just need to modify [this section](https://github.com/choderalab/clusterutils/blob/master/clusterutils/build_mpirun_configfile.py#L83-L86) to instead write properly-formatted commands to span multiple lines as suggested by the [mpirun man pages](http://linuxcommand.org/man_pages/mpiexec1.html).

Can someone take a stab at this?

**Comment by andrrizzi** [comment]
I'll take a look at this and see if I can figure it out.

**Comment by steven-albanese** [comment]
@andrrizzi figured it out! Seems we need to use `--mpitype conda` in the batch script when building the configfile

**Comment by jchodera** [comment]
Great, thanks!  Maybe we can make this the default for `build_mpirun_configfile`?

**Comment by steven-albanese** [comment]
hmm but now I'm seeing this error as the calculation is going on 

```
Traceback (most recent call last):
  File "/cbio/jclab/home/albaness/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
    yaml_builder.build_experiment()
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1263, in build_experiment
    self._run_experiment(combination, output_dir)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1874, in _run_experiment
    yank.run()
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yank.py", line 456, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 862, in run
    self._write_iteration_netcdf()
  File "/cbio/jclab/home/albaness/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/repex.py", line 1795, in _write_iteration_netcdf
    self.ncfile.variables['positions'][self.iteration,replica_index,:,:] = x[:,:]
  File "netCDF4/_netCDF4.pyx", line 3920, in netCDF4._netCDF4.Variable.__setitem__ (netCDF4/_netCDF4.c:42306)
  File "netCDF4/_netCDF4.pyx", line 4129, in netCDF4._netCDF4.Variable._put (netCDF4/_netCDF4.c:44159)
RuntimeError: NetCDF: HDF error
```

**Comment by jchodera** [comment]
Open a new issue for that?

Also, who wants to fix the default for `build_mpirun_configfile`?

**Comment by andrrizzi** [comment]
> Also, who wants to fix the default for `build_mpirun_configfile`

I can do that, but I'd wait until we figure out that the new error Steven is seeing is not related to the new configuration.

**Comment by jchodera** [comment]
I think that error is just that the NetCDF file was created by a previous call to YANK that failed partway through NetCDF creating and @steven-albanese didn't delete the old NetCDF files before running YANK again.  Or that there were two instances running at once.  I'd just make sure all YANK processes are terminated, delete the NetCDF files, and try again.

Also, please paste the stuff that happened before that. We need to know whether the different YANK processes were running with different process numbers or if they all think they are process 0 (master) and are trying to write to the same NetCDF file.

**Comment by andrrizzi** [comment]
> if they all think they are process 0 (master)

This was it! We just forgot to revert the `mpi` option in the YAML file while trying different things. It's working now. I'll change the default type to `conda`.

**Comment by andrrizzi** [comment]
Ok, I've open a PR that set `conda` as the default `mpitype` so if you happen to find a problem like this again, try to update `clusterutils`. Closing for now.
