### ISSUE TITLE
Check for existence of specified YAML file, raising an informative error message if not found

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#375]
I'm getting the following error with the 0.8.0 conda package:
```
Running simulation via MPI...
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
    dispatched = getattr(commands, command).dispatch(args)
    dispatched = getattr(commands, command).dispatch(args)
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 33, in dispatch
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 33, in dispatch
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 33, in dispatch
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 33, in dispatch
    yaml_builder = YamlBuilder(yaml_source=args['--yaml'])
    yaml_builder = YamlBuilder(yaml_source=args['--yaml'])
    yaml_builder = YamlBuilder(yaml_source=args['--yaml'])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in __init__
    yaml_builder = YamlBuilder(yaml_source=args['--yaml'])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in __init__
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in __init__
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in __init__
    for key in ['options', 'molecules', 'solvents', 'protocols']})
    for key in ['options', 'molecules', 'solvents', 'protocols']})
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in <dictcomp>
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in <dictcomp>
    for key in ['options', 'molecules', 'solvents', 'protocols']})
    for key in ['options', 'molecules', 'solvents', 'protocols']})
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in <dictcomp>
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1228, in <dictcomp>
    for key in ['options', 'molecules', 'solvents', 'protocols']})
    for key in ['options', 'molecules', 'solvents', 'protocols']})
AttributeError: 'str' object has no attribute 'get'
AttributeError: 'str' object has no attribute 'get'
        for key in ['options', 'molecules', 'solvents', 'protocols']})
for key in ['options', 'molecules', 'solvents', 'protocols']})
AttributeError: AttributeError: 'str' object has no attribute 'get'
'str' object has no attribute 'get'
```

**Comment by jchodera** [comment]
This appears to have been by the `yank.yaml` file specified in the `--yaml=yank.yaml` argument to `yank` not being present.  We should add some checking to make sure the file exists and produce a more informative error message.
