### ISSUE TITLE
Jenkins error

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#407]
@andrrizzi : Any ideas what this means?

```
======================================================================
ERROR: yank.tests.test_examples.test_examples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/tests/test_examples.py", line 110, in test_examples
    run_example(path, directory)
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/tests/test_examples.py", line 87, in run_example
    raise Exception('Example %s returned exit code %d' % (example, returncode))
Exception: Example mhc-peptide-tcr returned exit code 1
```

**Comment by andrrizzi** [comment]
Not so sure, I'll have to check the python script. In general though, I don't expect all examples to work at the moment. For example `abl-imatinib-explicit` has a `yank.yaml` (which tells `test_examples` to test through yaml) but in the `run.sh` script, it uses the CLI. I'll work on this when I'll revamp the examples in issue #391 .

**Comment by andrrizzi** [comment]
So the issue with the `mhc-peptide-tcr.py` script in Jenkins could be both of these:
1. the script requires `pdbfixer` but Yank doesn't.
2. the script passes the platform to Yank as `kwargs` (which is copied to avoid modifications) but it cannot be copied
```python
>>> import copy
>>> from simtk import openmm
>>> d = {'platform': openmm.Platform.getPlatformByName('CPU')}
>>> copy.deepcopy(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
TypeError: can't pickle SwigPyObject objects
```
**note that the `platform` option currently does not work in Yank**. It's always been there, but it wasn't attached to anything. Yank currently just select the fastest platform.

**Comment by Lnaden** [comment]
Do we want to have Jenkins tests up before 1.0? If so, can we resolve this issue before 1.0? I'm not sure there will be time given the other laundry list of issues we want to get done before then.

**Comment by andrrizzi** [comment]
I think this example was deleted with the creation of `yank-examples` repo. It will be obsolete after API refactoring anyway.

**Comment by Lnaden** [comment]
Okay, reducing priority level and we can close once it has been truly obsolete'd

**Comment by jchodera** [comment]
I don't yet have an ETA on fixing this. I'm waiting on a new SSL cert from MSKCC.

For now, we're focusing on using `yank-examples` or `yank-validation` to as a test suite that we can run on `hal`.

**Comment by jchodera** [comment]
We don't use Jenkins anymore, so closing this.
