### ISSUE TITLE
test_examples error 

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#457]
There seems to be an actual error occuring on [jenkins](https://jenkins.choderalab.org/job/test-yank-linux-xeon-gtxtitan-jak/36/console):

```
yank.tests.test_examples.test_examples ... Running simulation...
2016-08-20 10:26:32,402: MPI disabled.
2016-08-20 10:26:32,404: ERROR - yank.yamlbuild - Molecule lapatinib: Missing keys: 'filepath'
Traceback (most recent call last):
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.1.dev0', 'console_scripts', 'yank')()
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/cli.py", line 121, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/commands/script.py", line 40, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1199, in __init__
    self.parse(yaml_source)
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1259, in parse
    self._db.molecules = self._validate_molecules(yaml_content.get('molecules', {}))
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/yamlbuild.py", line 1570, in _validate_molecules
    raise YamlParseError('Molecule {}: {}'.format(molecule_id, e.autos[-1]))
yank.yamlbuild.YamlParseError: Molecule lapatinib: Missing keys: 'filepath'
Analyzing data...
2016-08-20 10:26:33,464: ERROR - yank.analyze - Cannot find analysis.yaml script in /home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/../examples/human-serum-albumin-explicit-yaml/testoutput/experiments
Traceback (most recent call last):
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.1.dev0', 'console_scripts', 'yank')()
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/cli.py", line 121, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/commands/analyze.py", line 29, in dispatch
    analyze.analyze(args['--store'])
  File "/home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/analyze.py", line 442, in analyze
    raise RuntimeError(err_msg)
RuntimeError: Cannot find analysis.yaml script in /home/jenkins/workspace/test-yank-linux-xeon-gtxtitan-jak/miniconda/lib/python2.7/site-packages/yank/../examples/human-serum-albumin-explicit-yaml/testoutput/experiments
ERROR
```

**Comment by andrrizzi** [comment]
Ah! Thanks for catching this. The YAML script still uses the old syntax to specify parameters. I can fix it easily.

**Comment by Lnaden** [comment]
Examples have been moved, closing this issue as the `test_examples` will be transfered eventually anyways.
