### ISSUE TITLE
Add test for extract-trajectory

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#460]
I may not be using this correctly:

```
[chodera@mskcc-ln1 hydration-smiles]$ yank analyze extract-trajectory --trajectory=molecule11-solvent2-replica0.pdb --replica=0 --netcdf experiments/hydrationsystemmolecule11/solvent2.nc
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.1.dev0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank/cli.py", line 121, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank/commands/analyze.py", line 27, in dispatch
    return dispatch_extract_trajectory(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank/commands/analyze.py", line 59, in dispatch_extract_trajectory
    analyze.extract_trajectory(output_path, nc_path, **kwargs)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank/analyze.py", line 642, in extract_trajectory
    serialized_topology = nc_file.groups('metadata').variables['topology'][0]
TypeError: 'OrderedDict' object is not callable
```

**Comment by jchodera** [comment]
Reopening to remind us to add tests for `yank analyze extract-trajectory`.

**Comment by andrrizzi** [comment]
The test was added in #743.
