### ISSUE TITLE
Binding replicas to different platforms 

### ISSUE THREAD

**Issue by msultan** [choderalab/yank#602]
Hello everyone, 
Thanks for making this package! I am trying to do a simple Hamiltonian or Replica exchange simulation where I would like simulation objects to use multiple available gpus. 

Naively, i would have thought that the Hamiltonian exchange object would take in a series of simulation objects where each simulation is bound to a platform and the exchange swaps out the state every n steps. However, the code seems to take in the systems objects only which makes me think that its creating the integrator and platform objects somewhere internally. Are those options exposed somewhere or can i pass a list of GPU indices to them? 

Here is what i have right now based off the yank website. 

```bash 
nvidia-smi 
Thu Dec  8 10:03:32 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
| N/A   26C    P8    28W / 175W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:09:00.0     Off |                    0 |
| N/A   23C    P8    28W / 175W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
```

here is the python script
``` python 
cat test.py 
#!/bin/env python
from simtk import openmm as mm
from yank.repex import *
from openmmtools import testsystems
from mpi4py import MPI
testsystem = testsystems.AlanineDipeptideImplicit()
[base_system, positions] = [testsystem.system, testsystem.positions]
# Copy baseline system.
systems = [base_system for index in range(2)]
# Create temporary file for storing output.
import tempfile
file = tempfile.NamedTemporaryFile() # temporary file for testing
store_filename = "./test.dat"#file.name
# Create baseline state.
base_state = ThermodynamicState(base_system, temperature=298.0*unit.kelvin)
# Create simulation.
simulation = HamiltonianExchange(store_filename,mpicomm=MPI.COMM_WORLD)
simulation.create(base_state, systems, positions)
simulation.number_of_iterations = 2 # set the simulation to only run 2 iterations
simulation.timestep = 2.0 * unit.femtoseconds # set the timestep for integration
simulation.nsteps_per_iteration = 50 # run 50 timesteps per iteration
simulation.minimize = False
# Run simulation.
simulation.run() 
```

and here is the error i get. 

``` bash
mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py  : -np 1 -env CUDA_VISIBLE_DEVICES 1 python test.py
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    simulation.create(base_state, systems, positions)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/yank/repex.py", line 2773, in create
    ReplicaExchange.create(self, states, positions, options=options, metadata=metadata)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/yank/repex.py", line 692, in create
    self._initialize_create()
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/yank/repex.py", line 975, in _initialize_create
    self.ncfile.close()
AttributeError: 'HamiltonianExchange' object has no attribute 'ncfile'

```

I am certain, I am doing something incredibly dumb here but i cant figure out what. Any help would be greatly appreciated.

Cheers!

**Comment by msultan** [comment]
changing test.py back to ```file.name``` instead of  ```test.dat``` doesnt change the error. 
``` bash
 mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py  : -np 1 -env CUDA_VISIBLE_DEVICES 1 python test.py
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    simulation.create(base_state, systems, positions)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/yank/repex.py", line 2773, in create
    ReplicaExchange.create(self, states, positions, options=options, metadata=metadata)
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/yank/repex.py", line 692, in create
    self._initialize_create()
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/yank/repex.py", line 975, in _initialize_create
    self.ncfile.close()
AttributeError: 'HamiltonianExchange' object has no attribute 'ncfile'

^CCtrl-C caught... cleaning up processes

```


Using a single GPU seems to work just fine 
``` bash 
mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py


 nvidia-smi 
Thu Dec  8 10:10:54 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
| N/A   31C    P0    69W / 175W |     66MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:09:00.0     Off |                    0 |
| N/A   23C    P8    28W / 175W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     69370    C   python                                          64MiB |
+-----------------------------------------------------------------------------+
```

**Comment by Lnaden** [comment]
Thanks for reporting this. I'm debugging it right now, thanks for the test case.

Most of our personal test cases don't use that function much, so there may be some bug we missed. We are also working on overhauling the Python API on the underside, so I cant promise this wont change at some point but anything you find that is lacking/incorrect in documentation, please let us know!

[Here is the code](https://github.com/choderalab/yank/blob/15c99205cf5fb340adf03b03dc7d8ea6579f1401/Yank/repex.py#L1230-L1232) in the `repex` object that generates the integrator and context. The basic `repex` objects do this every iteration which can be a bit slow depending on the size of your system.

**Comment by Lnaden** [comment]
@andrrizzi any ideas on this? I know its related the ncfile not being made available to all the MPI copies, but I can't figure out why `HamiltonianExchange` has this issue but `ModifiedHamiltonianExchange` does not.

**Comment by andrrizzi** [comment]
Hi @msultan! I just took a brief look at your script but I think you want also to add
```python
positions = [positions for index in range(2)]
```
as `HamiltonianExchange` expects a list of positions, one for each system. This may fix it, but let me know if you still get the error.

**Comment by andrrizzi** [comment]
Ah no, I forgot that the superclass should handle both. Investigating.

**Comment by andrrizzi** [comment]
From the error it kind of looks like every replica believes it's `rank 0`. What command are you using to run the script with MPI?

**Comment by andrrizzi** [comment]
Again, sorry. You listed it right there, I'll try to reproduce it.

**Comment by andrrizzi** [comment]
Hmm. I think we have never implemented the support for parallel phase creation. I think you will have to either have two separates scripts (one for creation and one that resumes and run) or to run `simulation.create()` only if `rank == 0`, place a barrier to sync the mpi processes after that and do `simulation.create('ncfile.dat')` for all other ranks before running.

Sorry I'm a little bit in a rush now, but I'll add an example script shortly.

**Comment by andrrizzi** [comment]
Let me know if this work!
```python
mpicomm = MPI.COMM_WORLD
simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
if mpicomm.rank == 0:
    simulation.number_of_iterations = 2 # set the simulation to only run 2 iterations
    simulation.timestep = 2.0 * unit.femtoseconds # set the timestep for integration
    simulation.nsteps_per_iteration = 50 # run 50 timesteps per iteration
    simulation.minimize = False
    simulation.create(base_state, systems, positions)
self.mpicomm.barrier()  # Sync MPI processes.
if mpicomm.rank != 0:
    simulation.resume()
simulation.run()
```

**Comment by msultan** [comment]
Thanks a lot for investigating this @Lnaden and @andrrizzi . I really appreciate it. Right now, the non 0  mpi ranks cant seem to find the netcdf file. 
``` python 

#!/bin/env python
from simtk import openmm as mm
from yank.repex import *
from openmmtools import testsystems
from mpi4py import MPI
import time
testsystem = testsystems.AlanineDipeptideImplicit()
[base_system, positions] = [testsystem.system, testsystem.positions]
# Copy baseline system.
systems = [base_system for index in range(2)]
# Create temporary file for storing output.
import tempfile
file = tempfile.NamedTemporaryFile() # temporary file for testing
store_filename = "test.dat"#file.name
# Create baseline state.
base_state = ThermodynamicState(base_system, temperature=298.0*unit.kelvin)
# Create simulation.
mpicomm = MPI.COMM_WORLD
simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
if mpicomm.rank == 0:
    simulation.number_of_iterations = 2 # set the simulation to only run 2 iterations
    simulation.timestep = 2.0 * unit.femtoseconds # set the timestep for integration
    simulation.nsteps_per_iteration = 50 # run 50 timesteps per iteration
    simulation.minimize = False
    simulation.create(base_state, systems, positions)
    mpicomm.barrier()  # Sync MPI processes.

# Run simulation.
if mpicomm.rank != 0:
    simulation.resume()

simulation.run()
```
```bash
which mpirun
~/software/anaconda/bin/mpirun

mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py  : -np 1 -env CUDA_VISIBLE_DEVICES 1 python test.py
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    simulation.resume()
  File "/home/msultan/software/anaconda/lib/python3.5/site-packages/yank/repex.py", line 713, in resume
    raise Exception("NetCDF file %s does not exist; cannot resume." % self.store_filename)
Exception: NetCDF file test.dat does not exist; cannot resume.

```

i am not sure whether the error is coming from my mpi or not . I also tried adding a bunch of sleep time for the non-zero mpi ranks but that didnt seem to help. Thanks again for all the help!

**Comment by msultan** [comment]
The file does seem to be created by the rank 0 though so i dont think its a permission or disk issue. 

``` bash
ls
simulate.py  test.dat  test.py

```

**Comment by jchodera** [comment]
I think I ran into the same issue recently, and put together a bugfix that may not have been merged in a PR. Let me dig it up in the morning.

**Comment by andrrizzi** [comment]
Hi @msultan, no problem! I'm not sure if it's only an indentation typo in your script, but the `mpicomm.barrier()` statement must be outside the `if mpicomm.rank == 0`, or the non-0 rank process won't wait for `rank 0` to create the file.

**Comment by msultan** [comment]
@jchodera Take your time! I am across the world right now so there is a large time-zone difference. 

@andrrizzi now i am getting an even weirder mpi issue when i move the barrier outside. 
``` bash 
mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py  : -np 1 -env CUDA_VISIBLE_DEVICES 1 python test.py
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    mpicomm.barrier()  # Sync MPI processes.
  File "MPI/Comm.pyx", line 1271, in mpi4py.MPI.Comm.barrier (src/mpi4py.MPI.c:108689)
  File "MPI/msgpickle.pxi", line 583, in mpi4py.MPI.PyMPI_barrier (src/mpi4py.MPI.c:46693)
mpi4py.MPI.Exception: Message truncated, error stack:
PMPI_Barrier(430)...................: MPI_Barrier(MPI_COMM_WORLD) failed
MPIR_Barrier_impl(337)..............: Failure during collective
MPIR_Barrier_impl(330)..............: 
MPIR_Barrier(294)...................: 
MPIR_Barrier_intra(151).............: 
barrier_smp_intra(111)..............: 
MPIR_Bcast_impl(1462)...............: 
MPIR_Bcast(1486)....................: 
MPIR_Bcast_intra(1295)..............: 
MPIR_Bcast_binomial(241)............: 
MPIC_Recv(352)................

```

**Comment by jchodera** [comment]
It looks like something is dying due to an exception but the exception message is not being printed.
* Are there errors when you run serially?
* Are you using the conda-installed mpi4py?

**Comment by msultan** [comment]
> Are there errors when you run serially?
- no errors when i use a single gpu 
``` bash
mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py

/home/msultan/software/anaconda/lib/python3.5/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting Replica States dtype=int32 to <class 'numpy.int64'> 
  TypeCastPerformanceWarning)

```
> Are you using the conda-installed mpi4py?
- yep, its 
``` bash 
which mpirun 
~/software/anaconda/bin/mpirun
```

**Comment by andrrizzi** [comment]
Ah! For some reason, the root process apparently invokes a `mpicomm.bcast()` in `ReplicaExchange.create()`, so I think your child process expect a barrier signal, and when it receives something else it complains. We need to fix it (sorry!), but as a temporary workaround, you could try something like (untested)
```python
simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
if mpicomm.rank == 0:
    simulation.number_of_iterations = 2 # set the simulation to only run 2 iterations
    simulation.timestep = 2.0 * unit.femtoseconds # set the timestep for integration
    simulation.nsteps_per_iteration = 50 # run 50 timesteps per iteration
    simulation.minimize = False
    simulation.create(base_state, systems, positions)
    mpicomm.barrier()
else:
    mpicomm.bcast(_, root=0)  # useless, but it may work
    mpicomm.barrier()
    simulation.resume()

simulation.run()
```

**Comment by msultan** [comment]
nope that didnt work either :(

```bash 
mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py  : -np 1 -env CUDA_VISIBLE_DEVICES 1 python test.py
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    mpicomm.bcast(_, root=0)  # useless, but it may work
NameError: name '_' is not defined
```

**Comment by andrrizzi** [comment]
Sorry, my original script was incorrect, I've edited now. Last attempt before I give up for today.

**Comment by msultan** [comment]
that didnt work either, thanks for all the help today though!
``` bash 
pirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py  : -np 1 -env CUDA_VISIBLE_DEVICES 1 python test.py
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    mpicomm.barrier()
  File "MPI/Comm.pyx", line 1271, in mpi4py.MPI.Comm.barrier (src/mpi4py.MPI.c:108689)
  File "MPI/msgpickle.pxi", line 583, in mpi4py.MPI.PyMPI_barrier (src/mpi4py.MPI.c:46693)
mpi4py.MPI.Exception: Message truncated, error stack:
PMPI_Barrier(430)...................: MPI_Barrier(MPI_COMM_WORLD) failed
MPIR_Barrier_impl(337)..............: Failure during collective
MPIR_Barrier_impl(330)..............: 
MPIR_Barrier(294)...................: 
MPIR_Barrier_intra(151).............: 
barrier_smp_intra(111)..............: 
```

**Comment by jchodera** [comment]
@andrrizzi, that was exactly the problem I had run into as well. I'm not sure why I didn't submit a fix at the time---there about that.

**Comment by andrrizzi** [comment]
Auch! Maybe the idea of my original script was correct after all. Last attempt for reals (this should fix at least the `NameError`)
```python
if mpicomm.rank == 0:
    simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
    simulation.number_of_iterations = 2 # set the simulation to only run 2 iterations
    simulation.timestep = 2.0 * unit.femtoseconds # set the timestep for integration
    simulation.nsteps_per_iteration = 50 # run 50 timesteps per iteration
    simulation.minimize = False
    simulation.create(base_state, systems, positions)
    del simulation
else:
    dummy_var = False
    mpicomm.bcast(dummy_var, root=0)
mpicomm.barrier()
simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
simulation.resume()

simulation.run()
```
Hope this works!

**Comment by msultan** [comment]
hmm, back to the barrier error. 

``` python
#!/bin/env python
from simtk import openmm as mm
from yank.repex import *
from openmmtools import testsystems
from mpi4py import MPI
import time
testsystem = testsystems.AlanineDipeptideImplicit()
[base_system, positions] = [testsystem.system, testsystem.positions]
# Copy baseline system.
systems = [base_system for index in range(2)]
# Create temporary file for storing output.
import tempfile
file = tempfile.NamedTemporaryFile() # temporary file for testing
store_filename = "test.dat"#file.name
# Create baseline state.
base_state = ThermodynamicState(base_system, temperature=298.0*unit.kelvin)
# Create simulation.
mpicomm = MPI.COMM_WORLD
if mpicomm.rank == 0:
    simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
    simulation.number_of_iterations = 2 # set the simulation to only run 2 iterations
    simulation.timestep = 2.0 * unit.femtoseconds # set the timestep for integration
    simulation.nsteps_per_iteration = 50 # run 50 timesteps per iteration
    simulation.minimize = False
    simulation.create(base_state, systems, positions)
    del simulation
else:
    dummy_var = False
    mpicomm.bcast(dummy_var, root=0)
mpicomm.barrier()
simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
simulation.resume()

simulation.run()
```


and here is the error 
``` bash 
mpirun -hosts gpu-27-21 -np 1 -env CUDA_VISIBLE_DEVICES 0 python test.py  : -np 1 -env CUDA_VISIBLE_DEVICES 1 python test.py
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    mpicomm.barrier()
  File "MPI/Comm.pyx", line 1271, in mpi4py.MPI.Comm.barrier (src/mpi4py.MPI.c:108689)
  File "MPI/msgpickle.pxi", line 583, in mpi4py.MPI.PyMPI_barrier (src/mpi4py.MPI.c:46693)
mpi4py.MPI.Exception: Message truncated, error stack:
PMPI_Barrier(430)...................: MPI_Barrier(MPI_COMM_WORLD) failed
MPIR_Barrier_impl(337)..............: Failure during collective
MPIR_Barrier_impl(330)..............: 
MPIR_Barrier(294)...................: 

```

**Comment by msultan** [comment]
I will use the single GPU version for now but will leave this issue open so that the devs can refer back to it as needed. Thanks again for all the help everyone.

**Comment by andrrizzi** [comment]
Sorry! I forgot about this. This trick works for me with two GPUs. Let me know if it fixes for you.
```python
mpicomm = MPI.COMM_WORLD
if mpicomm.rank == 0:
    simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
    simulation.number_of_iterations = 2 # set the simulation to only run 2 iterations
    simulation.timestep = 2.0 * unit.femtoseconds # set the timestep for integration
    simulation.nsteps_per_iteration = 50 # run 50 timesteps per iteration
    simulation.minimize = False
    simulation.create(base_state, systems, positions)
    del simulation
else:
    dummy_var = False
    mpicomm.bcast(dummy_var, root=0)
    mpicomm.bcast(dummy_var, root=0)
mpicomm.barrier()
simulation = HamiltonianExchange(store_filename, mpicomm=mpicomm)
simulation.resume()

simulation.run()
```

**Comment by msultan** [comment]
yayy! its working now. Thanks so much for all your help @andrrizzi ! 
```bash 
nvidia-smi 
Sat Dec 10 22:38:28 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:0A:00.0     Off |                    0 |
| N/A   29C    P0    79W / 175W |     65MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:85:00.0     Off |                    0 |
| N/A   43C    P0    86W / 175W |     65MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     44907    C   python                                          63MiB |
|    1     44908    C   python                                          63MiB |
```

**Comment by msultan** [comment]
For the sake of full records, this solution works with yank version 0.14.1 and openmm version 7.0.1.dev-5e86c4f.  Thanks again for all the help everyone!

**Comment by andrrizzi** [comment]
No problem!

**Comment by msultan** [comment]
closing this for now.
