### ISSUE TITLE
Freesolv example issues

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#619]
On a fresh installation of `yank` and `yank-examples`, I get the following error when trying to run the `freesolv-mini` example:
```
-bash-4.2$ cat ~/freesolv.o144 
Running simulation via MPI...
2016-12-27 17:05:27,999: MPI enabled.
2016-12-27 17:05:28,005: ERROR - yank.yamlbuild - Solvent solvents: None should be instance of 'dict'
2016-12-27 17:05:28,006: ERROR - yank.yamlbuild - Solvent solvents: None should be instance of 'dict'
2016-12-27 17:05:28,007: ERROR - yank.yamlbuild - Solvent solvents: None should be instance of 'dict'
2016-12-27 17:05:28,007: ERROR - yank.yamlbuild - Solvent solvents: None should be instance of 'dict'
Traceback (most recent call last):
  File "/home/chodera/miniconda/lib/python3.5/site-packages/schema-0.6.2-py3.5.egg/schema.py", line 225, in validate
  File "/home/chodera/miniconda/lib/python3.5/site-packages/schema-0.6.2-py3.5.egg/schema.py", line 74, in validate
schema.SchemaError: Or({Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89400>), Optional('solute_dielectric'): <class 'float'>, Optional('rigid_water'): <class 'bool'>, Optional('solvent_dielectric'): <class 'float'>, Optional('clearance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89620>), Optional('remove_c_m_motion'): <class 'bool'>, Optional('constraints'): <class 'object'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('positive_ion'): <class 'str'>, Optional('negative_ion'): <class 'str'>, Optional('implicit_solvent_kappa'): <class 'object'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89598>), Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89488>), Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89510>), 'nonbonded_method': Use(<function YamlBuilder._validate_solvents.<locals>.to_explicit_solvent at 0x7ff122c892f0>)}, {Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c896a8>), Optional('solvent_dielectric'): <class 'float'>, Optional('constraints'): <class 'object'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('nonbonded_method'): Use(<function YamlBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7ff122c89378>), Optional('hydrogen_mass'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89730>), Optional('solute_dielectric'): <class 'float'>, Optional('ewald_error_tolerance'): <class 'float'>, 'implicit_solvent': Use(<function to_openmm_app at 0x7ff123af4378>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89840>), Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c897b8>)}, {Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c899d8>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('constraints'): <class 'object'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c898c8>), Optional('hydrogen_mass'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89950>), Optional('ewald_error_tolerance'): <class 'float'>, Optional('implicit_solvent_kappa'): <class 'object'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89a60>), 'nonbonded_method': Use(<function YamlBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7ff122c89378>)}) did not validate None
None should be instance of 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/yamlbuild.py", line 1647, in _validate_solvents
    validated_solvents[solvent_id] = solvent_schema.validate(solvent_descr)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/schema-0.6.2-py3.5.egg/schema.py", line 227, in validate
schema.SchemaError: Or({Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89400>), Optional('solute_dielectric'): <class 'float'>, Optional('rigid_water'): <class 'bool'>, Optional('solvent_dielectric'): <class 'float'>, Optional('clearance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89620>), Optional('remove_c_m_motion'): <class 'bool'>, Optional('constraints'): <class 'object'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('positive_ion'): <class 'str'>, Optional('negative_ion'): <class 'str'>, Optional('implicit_solvent_kappa'): <class 'object'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89598>), Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89488>), Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89510>), 'nonbonded_method': Use(<function YamlBuilder._validate_solvents.<locals>.to_explicit_solvent at 0x7ff122c892f0>)}, {Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c896a8>), Optional('solvent_dielectric'): <class 'float'>, Optional('constraints'): <class 'object'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('nonbonded_method'): Use(<function YamlBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7ff122c89378>), Optional('hydrogen_mass'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89730>), Optional('solute_dielectric'): <class 'float'>, Optional('ewald_error_tolerance'): <class 'float'>, 'implicit_solvent': Use(<function to_openmm_app at 0x7ff123af4378>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89840>), Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c897b8>)}, {Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c899d8>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('constraints'): <class 'object'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c898c8>), Optional('hydrogen_mass'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89950>), Optional('ewald_error_tolerance'): <class 'float'>, Optional('implicit_solvent_kappa'): <class 'object'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7ff122c89a60>), 'nonbonded_method': Use(<function YamlBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7ff122c89378>)}) did not validate None
None should be instance of 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chodera/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.14.1', 'console_scripts', 'yank')()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/cli.py", line 74, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/commands/script.py", line 58, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/yamlbuild.py", line 1208, in __init__
    self.parse(yaml_source)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/yamlbuild.py", line 1278, in parse
    self._db.solvents = self._validate_solvents(yaml_content.get('solvents', {}))
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/yamlbuild.py", line 1649, in _validate_solvents
    raise YamlParseError('Solvent {}: {}'.format(solvent_id, e.autos[-1]))
yank.yamlbuild.YamlParseError: Solvent solvents: None should be instance of 'dict'

```

**Comment by jchodera** [comment]
@Lnaden : I think we really need to get that script working to run all the examples in parallel on our cluster. We should have some way to verify that all of these examples actually work with our release.

**Comment by jchodera** [comment]
This was with the `0.14.1` conda package:
```
-bash-4.2$ conda list | grep yank
yank                      0.14.1                   py35_0    omnia
```
and the current `yank-examples` github `master`.

**Comment by Lnaden** [comment]
> I think we really need to get that script working to run all the examples

That is on my chopping block for tonight/tomorrow.

**Comment by jchodera** [comment]
This still doesn't work eight months later, @Lnaden. Here's what I get with YANK 0.17.0 and a fresh checkout of `yank-examples` when running `yank-examples/examples/hydration/freesolv`:
```
-bash-4.1$ ./run-yank.sh 
Running simulation...
2017-09-04 12:18:25,052: Setting CUDA platform to use precision model 'mixed'.
2017-09-04 12:18:25,057: ERROR - yank.experiment - Solvent solvents: None should be instance of 'dict'
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/schema-0.6.6-py3.6.egg/schema.py", line 291, in validate
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/schema-0.6.6-py3.6.egg/schema.py", line 113, in validate
schema.SchemaError: Or({Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e48c8>), Optional('constraints'): <class 'object'>, Optional('rigid_water'): <class 'bool'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4840>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e47b8>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4730>), Optional('gbsa_model'): <class 'str'>, 'nonbonded_method': Use(<function ExperimentBuilder._validate_solvents.<locals>.to_explicit_solvent at 0x7f2d3543ad08>), Optional('clearance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e46a8>), Optional('solvent_model'): <function ExperimentBuilder._validate_solvents.<locals>.is_supported_solvent_model at 0x7f2d353e4950>, Optional('positive_ion'): <class 'str'>, Optional('negative_ion'): <class 'str'>, Optional('ionic_strength'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4620>), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x7f2d35413a60>), [<class 'str'>])}}, {Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4598>), Optional('constraints'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4510>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4b70>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4bf8>), Optional('gbsa_model'): <class 'str'>, 'implicit_solvent': Use(<function to_openmm_app at 0x7f2d39802950>), Optional('nonbonded_method'): Use(<function ExperimentBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7f2d353e4ae8>), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x7f2d35413a60>), [<class 'str'>])}}, {Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4c80>), Optional('constraints'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4d08>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4d90>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4e18>), Optional('gbsa_model'): <class 'str'>, 'nonbonded_method': Use(<function ExperimentBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7f2d353e4ae8>), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x7f2d35413a60>), [<class 'str'>])}}) did not validate None
None should be instance of 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 1172, in _validate_solvents
    validated_solvents[solvent_id] = solvent_schema.validate(solvent_descr)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/schema-0.6.6-py3.6.egg/schema.py", line 293, in validate
schema.SchemaError: Or({Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e48c8>), Optional('constraints'): <class 'object'>, Optional('rigid_water'): <class 'bool'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4840>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e47b8>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4730>), Optional('gbsa_model'): <class 'str'>, 'nonbonded_method': Use(<function ExperimentBuilder._validate_solvents.<locals>.to_explicit_solvent at 0x7f2d3543ad08>), Optional('clearance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e46a8>), Optional('solvent_model'): <function ExperimentBuilder._validate_solvents.<locals>.is_supported_solvent_model at 0x7f2d353e4950>, Optional('positive_ion'): <class 'str'>, Optional('negative_ion'): <class 'str'>, Optional('ionic_strength'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4620>), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x7f2d35413a60>), [<class 'str'>])}}, {Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4598>), Optional('constraints'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4510>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4b70>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4bf8>), Optional('gbsa_model'): <class 'str'>, 'implicit_solvent': Use(<function to_openmm_app at 0x7f2d39802950>), Optional('nonbonded_method'): Use(<function ExperimentBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7f2d353e4ae8>), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x7f2d35413a60>), [<class 'str'>])}}, {Optional('nonbonded_cutoff'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4c80>), Optional('constraints'): <class 'object'>, Optional('implicit_solvent_salt_conc'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4d08>), Optional('implicit_solvent_kappa'): <class 'object'>, Optional('temperature'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4d90>), Optional('solute_dielectric'): <class 'float'>, Optional('solvent_dielectric'): <class 'float'>, Optional('remove_c_m_motion'): <class 'bool'>, Optional('hydrogen_mass'): <class 'object'>, Optional('ewald_error_tolerance'): <class 'float'>, Optional('switch_distance'): Use(<function to_unit_validator.<locals>._to_unit_validator at 0x7f2d353e4e18>), Optional('gbsa_model'): <class 'str'>, 'nonbonded_method': Use(<function ExperimentBuilder._validate_solvents.<locals>.to_no_cutoff at 0x7f2d353e4ae8>), Optional('leap'): {'parameters': And(Use(<function ExperimentBuilder.<lambda> at 0x7f2d35413a60>), [<class 'str'>])}}) did not validate None
None should be instance of 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.17.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/commands/script.py", line 110, in dispatch
    yaml_builder = ExperimentBuilder(script=yaml_path, job_id=job_id, n_jobs=n_jobs)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 558, in __init__
    self.parse(script)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 670, in parse
    self._db.solvents = self._validate_solvents(yaml_content.get('solvents', {}))
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 1174, in _validate_solvents
    raise YamlParseError('Solvent {}: {}'.format(solvent_id, e.autos[-1]))
yank.experiment.YamlParseError: Solvent solvents: None should be instance of 'dict'
Analyzing data...
2017-09-04 12:18:30,918: ERROR - yank.analyze - Cannot find analysis.yaml script in experiments
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.17.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/commands/analyze.py", line 81, in dispatch
    analyze.analyze_directory(args['--store'])
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.6/site-packages/yank/analyze.py", line 1378, in analyze_directory
    raise RuntimeError(err_msg)
RuntimeError: Cannot find analysis.yaml script in experiments
```
