### ISSUE TITLE
Cannot use pdb files as ligand

### ISSUE THREAD

**Issue by aghanbar** [choderalab/yank#638]
It seems that Yank only accepts mol2 files as ligands, while in my case I want to use a very short peptide as a ligand for the free energy calculation. It seems that even if I specify a pdb file as ligand, it still assumes that the ligand is mol2 and starts doing the procedures it usually does for mol2 files and as a result it fails. Can this issue be fixed?

> 

2017-02-08 12:39:45,145: MPI disabled.
2017-02-08 12:39:45,150: Setting up the systems for f_system, chain and pme
2017-02-08 12:40:14,320: Setting CUDA platform to use precision model 'mixed'.
Traceback (most recent call last):
  File "/root/anaconda2/envs/rezayank/bin/yank", line 11, in <module>
    load_entry_point('yank==0.15.0', 'console_scripts', 'yank')()
  File "/root/anaconda2/envs/rezayank/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/root/anaconda2/envs/rezayank/lib/python2.7/site-packages/yank/commands/script.py", line 100, in dispatch
    yaml_builder.build_experiments()
  File "/root/anaconda2/envs/rezayank/lib/python2.7/site-packages/yank/yamlbuild.py", line 1333, in build_experiments
    self._run_experiment(combination, output_dir)
  File "/root/anaconda2/envs/rezayank/lib/python2.7/site-packages/yank/yamlbuild.py", line 2447, in _run_experiment
    ligand_dsl = utils.Mol2File(ligand_descr['filepath']).resname
  File "/root/anaconda2/envs/rezayank/lib/python2.7/site-packages/yank/utils.py", line 1333, in resname
    return residue.name
AttributeError: 'Structure' object has no attribute 'name'

UPDATE: I noticed that you can convert the pdb to mol2 and use that instead.

**Comment by Lnaden** [comment]
We try to enforce that the ligand be in a file format that can support charges since there is no real standard library of partial charges on small molecules like there is protein residues. As such, we go with the mol2 format (or SMILES strings/Molecule name if you have the appropriate tools installed).

It looks like you found a way to convert, but in case you did not know:
If you installed YANK through `conda`, then you should also have access to the `antechamber` program through the `ambermini` package. It would be something like

```shell
$ antechamber -i mymol.pdb -fi pdb -o mymol.mol2 -fo mol2
```
so that would be _a_ way to convert the molecule. You would still want to charge it through the `antechamber` or `epik` flag(s) in the YAML file to get partial charges.

**Comment by jchodera** [comment]
I thought we had the ability to support PDB files as ligands, and I think we should have this capability if it can be supported by either the OEChem or antechamber ingestion workflows. We can generate the charges, rather than having the user supply them.

**Comment by aghanbar** [comment]
I still have problems even after I convert pdb to mol2. My peptide is supposed to be a normal peptide chain but for some reason it fails to be converted using antechamber. But I was able to convert it using pymol or chimera. Afterwards there are two scenarios:

**Comment by jchodera** [comment]
That's odd. @andrrizzi : Can you take a look at this?

**Comment by aghanbar** [comment]
After further analysis I found there is an ineherent issue with using proteins and peptides as ligands and it is because of the way Yank tries to distinguish the ligand from the rest of the system by using mdtraj to retrieve atom indices. Ligands in pdb files are denoted as Hetroatoms and can have a unique residue name that mdtraj uses to find the ligand. As for a normal peptide, no such thing as residue name is there to be used to select the ligand atoms so this fails:
Yank/pipeline.py
line 132
```
    # Determine ligand atoms
    atom_indices['ligand'] = mdtraj_top.select(ligand_dsl).tolist()
```
One way would be to convert the peptide atoms to hetroatoms and try to treat them as chemical structrues and  get the parameters using antechamber and so on which isn't rational. 
The better way would be to try to somehow change how the atom selection works. For example for peptides the selection can be based on the chain id.

**Comment by jchodera** [comment]
Thanks for tracking this down!

@andrrizzi and @Lnaden are out until next week, but we should be able to fix this up when they return.

If you're willing to create the solvated complex and ligand-in-solvent phases yourself, you could use provide these in AMBER or gromacs format [via this route](http://getyank.org/0.15.0/yamlpages/systems.html#yaml-systems-user-defined) if you want to work around this immediately. This scheme allows you to specify your own `ligand_dsl` string, where you can specify chain id, for example.

**Comment by andrrizzi** [comment]
Hi @aghanbar. Sorry, the automatic pipeline doesn't currently support peptide ligands (#376 is a related issue). We actually plan to add this as one of the first new features right after Yank 1.0, but for now I'd suggest you to prepare the complex with `tleap` yourself and provide the system `prmtop`/`inpcrd` files with [this syntax](http://getyank.org/0.15.0/yamlpages/systems.html#yaml-systems-user-defined). Let me know if I can help.

**Comment by aghanbar** [comment]
Thank you for the response. But I'm still having a problem. Here is how my yaml script looks like:

```
systems:
  model03:
    phase1_path: [complex.prmtop, complex.inpcrd]
    phase2_path: [solvent.prmtop, solvent.inpcrd]
    ligand_dsl: resname MOL
    solvent_dsl: resname WAT  # optional
    solvent: pme
    leap:
      parameters: [leaprc.protein.ff99SBildn, leaprc.gaff2, leaprc.water.tip3p]
```
And here is the error I get:
```
  File "/root/anaconda2/envs/rezayank/lib/python2.7/site-packages/yank/yamlbuild.py", line 1861, in _validate_systems
    raise YamlParseError('System {}: {}'.format(system_id, e.autos[-1]))
yank.yamlbuild.YamlParseError: System model03: _system_files(['solvent.prmtop', 'solvent.inpcrd']) raised RuntimeError("Wrong system file types provided.\nExtensions provided: ['inpcrd', 'prmtop']\nExpected extensions: ['pdb', 'xml']\n",)
```
Looks like it only accepts pdb and xml files in solvent section. But I see in the example in the link you provided that gromacs files are provided. 
Also, how one can specify ligand DSL based on residue names when only amber files are provided? I know that residue names like MOL and WAT can exist in pdb files but I am not sure that the same thing is possible in inpcrd and prmtop files?

**Comment by andrrizzi** [comment]
You are obtaining the error because you cannot specify parameters when the parameters have been already assigned by leap, so you should remove the `leap` section. I think in your case you can also drop `solvent_dsl`. If your solvent molecules don't have an uncommon resname, Yank should automatically find it.

> how one can specify ligand DSL based on residue names when only amber files are provided?

The residue name of the pdb used to construct the `prmtop`/`inpcrd` file is preserved through leap so resname usually works. However, you are dealing with a peptide, so I imagine the resname would be different than `MOL`, and you don't want to accidentally select parts of the receptor. I would check out [this page](http://mdtraj.org/1.8.0/atom_selection.html) for more advanced DSL syntax. When Yank starts, it prints out the number of alchemical atoms resulted with the givent `ligand_dsl`. If that's not the expected number of atoms for your peptide, it means something is wrong.

Hope this helps!

**Comment by aghanbar** [comment]
Thank you I think I was able to make it work. I used "resid from *some number* to *some other number*" to select the ligand. I noticed that leap appends the ligand in the end of the complex. So if my ligand has 6 residues the last 6 residues in the complex are the ligand. This may be useful for automation in the pipeline.

**Comment by andrrizzi** [comment]
> This may be useful for automation in the pipeline.

It is! Thanks for sharing.

**Comment by smsaladi** [comment]
I wonder if another approach here might be converting the initial pdb file to a mol2 with charges directly from the forcefield being used. Would this get around having to generate the two systems (phase1, phase2)? Am I missing something...?

**Comment by aghanbar** [comment]
> I wonder if another approach here might be converting the initial pdb file to a mol2 with charges directly from the forcefield being used.

At the time Yank automatically treated any provided ligand as a chemical molecule and sent it to Antechamber. Changing its way of doing things needed code modification. Of course, many approaches are possible. What you wanna do is to get what you want with the least amount of modifications to the program code.

**Comment by smsaladi** [comment]
Right, sorry, I should have been clearer. Since ligands as pdb files are not supported yet, I am looking for a work around that doesn't involve building the two systems, for right now.

In one of the examples here (https://github.com/choderalab/yank/blob/265c2d0def94c82184cc668beea6bfb2fbce12be/docs/yank-yaml-cookbook/combinatorial-experiment.yaml#L74) there is a note that charges can be picked up from the mol2 file by specifying "charge_method: null".

In principle then... If one could convert a pdb file of a protein ligand into a mol2 file pulling charges as specified in the chosen forcefield, this file could be specified to yank as the ligand along with "charge_method: null".

I guess, I was wondering if this approach is viable/equivalent to setting up the 2 systems beforehand as suggested above.

**Comment by jchodera** [comment]
@andrrizzi : Is it possible to have the `ligand:` in the `systems` block recorded as the 'ligand' even if it is constructed from a PDB file?

**Comment by jchodera** [comment]
@andrrizzi : I think I see the issue here. Let's chat about what a more general fix for this would look like. Presumably, it involves some extra bookkeeping to keep track of how different molecules defined by the user map into different atom indices of the resulting system(s)!
