### ISSUE TITLE
Example YAML files for alternate solvent systems

### ISSUE THREAD

**Issue by spadavec** [choderalab/yank#648]
Are there a collection of yaml file syntax/orders that are available for non-pme solvent systems? I'm still having issues getting `pme` to work, and would like to use `rf` in the mean time, but am getting a myriad of `lambda_restraints` errors that I don't quite understand.

**Comment by Lnaden** [comment]
The `nonbonded_method`s in the `solvents` section are linked directly to the `NonbondedMethod`s of OpenMM listed [here](http://docs.openmm.org/7.1.0/userguide/application.html?highlight=nonbonded#nonbonded-interactions). For Reaction Field, you will want to use `CutoffPeriodic`, but as we [note in the docs](http://getyank.org/0.15.2.dev0/yamlpages/solvents.html?highlight=cutoffperiodic#openmm-system-creation-options) there are some known errors with that in YANK.

What `lambda_restraints` errors are you getting, and what type of restraint are you trying to use?

**Comment by andrrizzi** [comment]
Can you post the `lambda_restraints` error you get and the script? It may be only a syntax error in the YAML script.

**Comment by spadavec** [comment]
Sorry for the long response time, but I tried to clean up my `yaml` file and am getting a different error: 

```
Traceback (most recent call last):
  File "/home/yanker/miniconda2/bin/yank", line 11, in <module>
    load_entry_point('yank==0.15.0', 'console_scripts', 'yank')()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/commands/script.py", line 100, in dispatch
    yaml_builder.build_experiments()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1331, in build_experiments
    self._setup_experiments()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 2100, in _setup_experiments
    self._db.get_system(system_id)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 677, in get_system
    0, system_parameters, solvent_id, ligand_id)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1096, in _setup_system
    warnings = tleap.run()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/utils.py", line 1612, in run
    raise RuntimeError(error_msg + ' Check log file {}'.format(log_path))
RuntimeError: Argument #2 is type String must be of type: [unit] Check log file /home/yanker/DD8A7B/setup/systems/4djw/solvent.leap.log
```
with the yaml file:
```
experiments: 
  protocol: absolute-binding 
  system: 4djw

molecules:
  4djw: 
    filepath: 4djw.pdb
  DD8A7B:
    antechamber: 
      charge_method: bcc
    filepath: DD8A7B.mol2

options: 
  minimize: yes
  number_of_iterations: 1000
  output_dir: .
  pressure: 1*atmosphere
  softcore_beta: 0.0
  temperature: 300*kelvin
  verbose: true

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.0, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55,
          0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0]
        lambda_sterics: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.95, 0.9, 0.85, 0.8, 0.75,
          0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.0]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.0, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55,
          0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0]
        lambda_sterics: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.95, 0.9, 0.85, 0.8, 0.75,
          0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.0]
solvents:
  rf: 
    clearance: 9*angstroms
    negative_ion: Cl-
    nonbonded_cutoff: 9*angstroms
    nonbonded_method: CutoffPeriodic
    positive_ion: Na+

systems:
  4djw:
    leap:
      parameters: [leaprc.ff14SB, leaprc.gaff, frcmod.ionsjc_tip3p]
    ligand: DD8A7B
    receptor: 4djw
    solvent: rf
```

in the `solvent.leap.log` file it mentions: 

```
> solvateBox DD8A7B TIP3PBOX 9.0 iso
solvateBox: Argument #2 is type String must be of type: [unit]
usage:  solvateBox <solute> <solvent> <buffer> [iso] [closeness]

```

**Comment by jchodera** [comment]
@andrrizzi : Could this be an issue with `leap` not liking the name `DD8A7B` for a small molecule? I think I've run into this before.

**Comment by andrrizzi** [comment]
It could be. Can you try removing the numbers from the systems and molecules identification names in the YAML file to see if it fixes it?

**Comment by spadavec** [comment]
Switching to all-letter names didn't fix the issue, but switching to all-letter names and PME instead did work?

**Comment by andrrizzi** [comment]
That's very weird! The `leap` script is not aware of what method is used. Can you share the input files? I could try to replicate and see what is the cause of the issue.

**Comment by spadavec** [comment]
well now I'm thoroughly spooked; re-running this on a different machine seems to run both rf and pme fine. I'll investigate this more and get back to you asap. Sorry for the hassle
