### ISSUE TITLE
Update openmoltools version number in conda recipe

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#658]
I just ran into this issue when I installed `yank` after having downgraded to `openmm==6.3.1` for another project:
```
-bash-4.1$ yank analyze extract-trajectory --help
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.15.2', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2202, in load
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2208, in resolve
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/yank/__init__.py", line 13, in <module>
    from . import utils
  File "/cbio/jclab/home/chodera/miniconda3/lib/python3.5/site-packages/yank/utils.py", line 26, in <module>
    from openmoltools.utils import wraps_py2, unwrap_py2  # Shortcuts for other modules
ImportError: cannot import name 'wraps_py2'
```
Upgrading `openmoltools` from `0.6.9` to `0.7.5` fixed the issue.
I think this means we need to update the `openmoltools` minimum required version number in the conda recipe.

**Comment by Lnaden** [comment]
Looks like this was fixed by #684
