### ISSUE TITLE
Conda packaging issues

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#67]
I've nearly created a proper conda package.

You can try checking it out with:
```
conda install -c https://conda.binstar.org/jchodera yank-dev
```

If you want to do this in an isolated conda repo, use
```
bash
conda create -p ~/yank/test/conda-env anaconda=2.0.0
source activate /cbio/jclab/home/chodera/yank/test/conda-env
```

I run into a problem with our `version` stuff:
```
(/cbio/jclab/home/chodera/yank/test/conda-env)bash-4.1$ python
iPython 2.7.7 |Anaconda 2.0.0 (64-bit)| (default, Jun 19 2014, 13:12:39) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import yank
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cbio/jclab/home/chodera/yank/test/conda-env/lib/python2.7/site-packages/yank/__init__.py", line 29, in <module>
    import version
ImportError: No module named version
```

Any ideas?

**Comment by jchodera** [comment]
Resolved!
