### ISSUE TITLE
Trouble parsing `gro` and `top` files

### ISSUE THREAD

**Issue by gregoryross** [choderalab/yank#672]
I'm trying to run a YANK calculation using `gromacs` system inputs. Following the example [here](http://getyank.org/0.15.2.dev0/yamlpages/cookbook.html), my `yaml` script includes the following entries:
```
systems:
  gromacs-system:
    phase1_path: [HV149/System/topol.top, HV149/System/6md_mol.gro]
    phase2_path: [HV149/ligand/lig.top, HV149/ligand/ions.gro]
    ligand_dsl: resname V49
    solvent_dsl: resname SOL 
    gromacs_include_dir: /cbio/jclab/home/rossg/gromacs/share/top/amber99sb-ildn.ff/ 
```
However, there seems to be a problem with the file types as I get the following error message when I run `yank`:
```
Wrong system file types provided.
Extensions provided: ['gro', 'top']
Expected extensions: ['inpcrd', 'prmtop']

Wrong system file types provided.
Extensions provided: ['gro', 'top']
Expected extensions: ['inpcrd', 'prmtop']

Correctly recognized files ['HV149/System/topol.top', 'HV149/System/6md_mol.gro'] as ['gro', 'top']
Correctly recognized files ['HV149/ligand/lig.top', 'HV149/ligand/ions.gro'] as ['gro', 'top']
Correctly recognized files ['HV149/System/topol.top', 'HV149/System/6md_mol.gro'] as ['gro', 'top']
Correctly recognized files ['HV149/ligand/lig.top', 'HV149/ligand/ions.gro'] as ['gro', 'top']
Correctly recognized files ['HV149/System/topol.top', 'HV149/System/6md_mol.gro'] as ['gro', 'top']
Correctly recognized files ['HV149/ligand/lig.top', 'HV149/ligand/ions.gro'] as ['gro', 'top']
Wrong system file types provided.
Extensions provided: ['gro', 'top']
Expected extensions: ['pdb', 'xml']

2017-05-04 11:45:20,121: ERROR - yank.yamlbuild - System gromacs-system: _system_files(['HV149/System/topol.top', 'HV149/System/6md_mol.gro']) raised RuntimeError("Wrong system file types provided.\nExtensions provided: ['gro', 'top']\nExpected extensions: ['pdb', 'xml']\n",)
Traceback (most recent call last):
  File "/cbio/jclab/home/rossg/miniconda2/bin/yank", line 11, in <module>
    load_entry_point('yank==0.15.2', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/rossg/miniconda2/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cbio/jclab/home/rossg/miniconda2/lib/python2.7/site-packages/yank/commands/script.py", line 97, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/cbio/jclab/home/rossg/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1221, in __init__
    self.parse(yaml_source)
  File "/cbio/jclab/home/rossg/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1314, in parse
    self._db.systems = self._validate_systems(yaml_content.get('systems', {}))
  File "/cbio/jclab/home/rossg/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1861, in _validate_systems
    raise YamlParseError('System {}: {}'.format(system_id, e.autos[-1]))
yank.yamlbuild.YamlParseError: System gromacs-system: _system_files(['HV149/System/topol.top', 'HV149/System/6md_mol.gro']) raised RuntimeError("Wrong system file types provided.\nExtensions provided: ['gro', 'top']\nExpected extensions: ['pdb', 'xml']\n",)
```
Are `gromacs` files not yet supported?

**Comment by jchodera** [comment]
I think this error means you simply have to specify the `gro` file first and then the `top` file in the list, rather than the other way around.

I agree this is highly nonintuitive and should be fixed.

**Comment by andrrizzi** [comment]
Hmm. The order of the file should not matter if I remember correctly. I'll take a look at this soon.

**Comment by andrrizzi** [comment]
I think your script missing the `solvent` key. There should be something like
```
solvents:
  PME-solvent:
    nonbonded_method: PME
    nonbonded_cutoff: 11*angstrom
    ...

systems:
  gromacs-system:
    phase1_path: [HV149/System/topol.top, HV149/System/6md_mol.gro]
    phase2_path: [HV149/ligand/lig.top, HV149/ligand/ions.gro]
    ligand_dsl: resname V49
    solvent_dsl: resname SOL 
    solvent: PME-solvent
    gromacs_include_dir: /cbio/jclab/home/rossg/gromacs/share/top/amber99sb-ildn.ff/
```
that info is needed for yank to know how to treat long-range interactions.

Sorry about the uninformative message. I still have to find a way to handle errors with schemas this complicated.

**Comment by andrrizzi** [comment]
Also, notice that if you specify `solvent_dsl: resname SOL` you need to have counterions named `SOL` too or yank won't treat them as solvent counterions. `SOL` is among the names automatically recognized by Yank so you can remove the `solvent_dsl` altogether. Alternatively you'll need to add manually the DSL of your counterions.

**Comment by gregoryross** [comment]
Thanks @andrrizzi! Adding `solvents` key removed that error. I'll close this issue.
