### ISSUE TITLE
Online analysis keywords problem

### ISSUE THREAD

**Issue by mmagithub** [choderalab/yank#724]
Hi,
I am trying to include the "online analysis keywords" in an explicit solvent YANK free energy calculations:
#######
---
options:
  minimize: yes
  minimize_max_iterations: 100
  number_of_equilibration_iterations: 500
  equilibration_timestep: 1.0*femtosecond
  verbose: yes
  number_of_iterations: 500
  nsteps_per_iteration: 500
  replica_mixing_scheme: swap-all
  collision_rate: 5.0/picosecond
  anisotropic_dispersion_correction: yes
  anisotropic_dispersion_cutoff: auto
  online_analysis_target_error: 1.0
  online_analysis_interval: 100
  online_analysis_minimum_iterations: 50
  temperature: 300*kelvin
  pressure: 1*atmosphere
  timestep: 2*femtoseconds
  output_dir: explicit
  platform: CUDA
  precision: auto
  constraints: HBonds
#######
But YANK keeps complaining with the follwoing error:

######
No handlers could be found for logger "yank.yamlbuild"
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/bin/yank", line 11, in <module>
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/commands/script.py", line 97, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1329, in __init__
    self.parse(yaml_source)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1408, in parse
    validate_general_options=True))
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1730, in _validate_options
    raise YamlParseError(str(e))
yank.yamlbuild.YamlParseError: found unknown parameter online_analysis_minimum_iterations, online_analysis_target_error, online_analysis_interval
No handlers could be found for logger "yank.yamlbuild"
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/bin/yank", line 11, in <module>
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/commands/script.py", line 97, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1329, in __init__
    self.parse(yaml_source)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1408, in parse
    validate_general_options=True))
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1730, in _validate_options
    raise YamlParseError(str(e))
yank.yamlbuild.YamlParseError: found unknown parameter online_analysis_minimum_iterations, online_analysis_target_error, online_analysis_interval
No handlers could be found for logger "yank.yamlbuild"
No handlers could be found for logger "yank.yamlbuild"
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/bin/yank", line 11, in <module>
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/bin/yank", line 11, in <module>
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/cli.py", line 71, in main
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/commands/script.py", line 97, in dispatch
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/commands/script.py", line 97, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1329, in __init__
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1329, in __init__
    self.parse(yaml_source)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1408, in parse
    self.parse(yaml_source)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1408, in parse
    validate_general_options=True))
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1730, in _validate_options
    validate_general_options=True))
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1730, in _validate_options
    raise YamlParseError(str(e))
    raise YamlParseError(str(e))
######

As you can see, the main complain is about not able to parse the online analysis keywords:

######
yank.yamlbuild.YamlParseError: found unknown parameter online_analysis_minimum_iterations, online_analysis_target_error, online_analysis_interval
######

These words should be given in the options list, right?
Any clue?

Regards,
Marawan

**Comment by Lnaden** [comment]
The online analysis feature is not part of a released version of YANK, it will be coming out with 0.17.0. Version 0.16.2 does not have that feature. If you want, you can install YANK from source right now to get the feature. So you would have a dev version of 0.17.0.

For other posts, if you want to drop in large code blocks like that, could you please encode them in triple back ticks like this \`\`\` block of code \`\`\` ? It makes multi-line code/output much easier to read

```
and it looks
like this
```

Thanks!

**Comment by Lnaden** [comment]
@mmagithub We have just cut YANK 0.17.0 which has the [online analysis](http://getyank.org/0.17.0/yamlpages/options.html?highlight=online#online-analysis-parameters) feature in it. Please download the new version and give it a try again. If you are still having issues, please feel free to open another issue!
