### ISSUE TITLE
NetCDF: HDF error after unexpected reboot

### ISSUE THREAD

**Issue by spadavec** [choderalab/yank#737]
I had a computer running an experiment and the computer rebooted in the middle for some reason; trying to restart the simulation with the existing YAML file produced: 

```
2017-07-30 16:08:39,261: Setting CUDA platform to use precision model 'mixed'.
2017-07-30 16:08:39,264: Single node: executing <function _check_resume at 0x7fc98f9ab230>
2017-07-30 16:08:39,265: Single node: executing <function _setup_experiments at 0x7fc98f9ab488>
2017-07-30 16:08:39,265: Setting up the systems for BRD4, jq1 and pme
2017-07-30 16:08:39,265: Single node: executing <function _safe_makedirs at 0x7fc98f9ab668>
2017-07-30 16:08:39,265: Single node: executing <bound method YamlBuilder._generate_yaml of <yank.yamlbuild.YamlBuilder object at 0x7fc98ed89090>>
2017-07-30 16:08:39,279: DSL string for the ligand: "resname LIG"
2017-07-30 16:08:39,279: DSL string for the solvent: "auto"
2017-07-30 16:08:39,280: Reading phase solvent
2017-07-30 16:08:39,280: prmtop: ./setup/systems/BRD4/solvent.prmtop
2017-07-30 16:08:39,280: inpcrd: ./setup/systems/BRD4/solvent.inpcrd
2017-07-30 16:08:39,795: solute_atoms net charge: 0
2017-07-30 16:08:39,796: Single node: executing <function _save_analysis_script at 0x7fc98f9ab500>
2017-07-30 16:08:39,796: Initial checkpoint file automatically chosen as ./experiments/complex_checkpoint.nc
Traceback (most recent call last):
  File "/home/yanker/miniconda2/bin/yank", line 11, in <module>
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/commands/script.py", line 100, in dispatch
    yaml_builder.run_experiments()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1464, in run_experiments
    experiment.run(n_iterations=switch_experiment_interval)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1188, in run
    alchemical_phase = AlchemicalPhase.from_storage(phase)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yank.py", line 386, in from_storage
    reporter.open(mode='r')
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/repex.py", line 221, in open
    primary_ncfiles['analysis'] = netcdf.Dataset(self._storage_file_analysis, mode, version='NETCDF4')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12626)
IOError: NetCDF: HDF error
```
I'm guessing the checkpoint file got corrupted somehow? Is there a known workaround to this, or does the entire calculation need to be re-run?

**Comment by jchodera** [comment]
It looks like that's the [analysis file, not the checkpoint file](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L250-L252) that somehow got corrupted. That unfortunately means that the simulation data collected so far can't be analyzed to estimate a binding free energy, but in principle we could extract the current simulation snapshots to resume the simulation if necessary.

It's odd that the analysis file would become corrupted since the critical failure window is so small for that file since so little data is being written. Though this is only true if we immediately call `sync()` on the NetCDF files to prevent data corruption immediately after writing each iteration's worth of data, which we definitely *used* to do, but I can't seem to find where we do that now after some storage restructuring.

@Lnaden @andrrizzi : Can you verify that we are calling `sync()` on the NetCDF files immediately after writing each iteration's worth of data? If this somehow got lost, we should add that back.

**Comment by jchodera** [comment]
@spadavec : Our plan is to eventually migrate to some sort of central networked high-availability concurrent database for safety, concurrency, and to support real-time analysis. That should eliminate all of these problems. Our top priority at the moment is to get the 1.0 release and paper out, however, so migration from file-based storage to network database storage will happen at some point thereafter.

**Comment by spadavec** [comment]
@jchodera Makes total sense; its not a problem for me at all (very excited to see your paper come out!). I wasn't sure how exactly the data was being stored, and was curious if there was a way to step back an arbitrary number of iterations and re-run the job from there.

**Comment by jchodera** [comment]
> I wasn't sure how exactly the data was being stored, and was curious if there was a way to step back an arbitrary number of iterations and re-run the job from there.

That's the intention with using the NetCDF files---if the last snapshot isn't fully written, it should just back up to the last good snapshot automatically and resume from there. Unfortunately, there are times when the NetCDF file itself can become corrupted, it seems. We tried to minimize that critical failure window to just a very small fraction of the runtime by using `sync()` after each iteration, but that may have been neglected in the latest storage restructuring. We'll try to get that fixed.

**Comment by jchodera** [comment]
Can you try `ncdump -h` on the NetCDF file to see if it can read it that way?

It's probably not `./experiments/complex_checkpoint.nc` but the other NetCDF file in that same directory.

**Comment by andrrizzi** [comment]
> by using sync() after each iteration, but that may have been neglected in the latest storage restructuring

We still do that [here](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L2065) at the end of each iteration.

Hmm. That sounds like a hard failure to recover from. It looks like netcdf can't even open the file, at least not in writing mode. You can try to do this
```python
import netCDF4 as netcdf
netcdf.Dataset('complex.nc', 'r', version='NETCDF4')
```
if this doesn't raise any error, there's a chance we can recover, otherwise I'm not sure there's a solution.

**Comment by spadavec** [comment]
Yeah, it looks like I can't actually open any of the NetCDF files; something very wonky must have happened while the computer booted down. In any case, I'll just restart the job. I presume its safe to close this case?

**Comment by andrrizzi** [comment]
Ok, sorry about that. I'll close the issue, feel free to reopen if you have news.

**Comment by jchodera** [comment]
Could the reboot have automatically updated or installed HDF5 or netcdf libraries via apt? Or could your miniconda path have been changed, or miniconda updated?

**Comment by Lnaden** [comment]
It could also be that the reboot happened while the NetCDF file was mid-write/sync, which would corrupt the file. @jchodera this happened on our cluster too, remember?
