### ISSUE TITLE
Error when using automatic alchemical path determination

### ISSUE THREAD

**Issue by elkhoury** [choderalab/yank#766]
As discussed in issue #749, we tried to compute the thermodynamic state spacing using the **auto** keyword, on two different complexes:
1- Cyclodextrin host/guest system. 
2- HSP90 protein/ligand system.

In both cases, YANK version 0.17.0 stops after the equilibration step.

We have attached input files to reproduce these cases.

Thank you,
Léa

(@davidlmobley, @renm1)
[harmonic_auto.tar.gz](https://github.com/choderalab/yank/files/1268391/harmonic_auto.tar.gz)

**Comment by jchodera** [comment]
> In both cases, YANK version 0.17.0 stops after the equilibration step.

Can you elaborate on what you mean by "stops"? Does it crash? Does it hang?

**Comment by elkhoury** [comment]
Please find attached the error files.

Thanks.
[auto_errors.tar.gz](https://github.com/choderalab/yank/files/1270969/auto_errors.tar.gz)

**Comment by davidlmobley** [comment]
Looks like a different assertion error in each case -- so a type of crash, though it's very opaque as to what the underlying reason is without digging into the code.

**Comment by jchodera** [comment]
For `hsp_90_80_harmonic_auto.e9577845`:
```
2017-08-28 18:27:21,111: Equilibration iteration 999/1000
2017-08-28 18:27:21,111: Propagating all replicas...
2017-08-28 18:27:21,111: Running _propagate_replica serially.
2017-08-28 18:27:23,558: Running _get_replica_move_statistics serially.
2017-08-28 18:27:23,558: Propagating all replicas took    2.446s
2017-08-28 18:27:23,558: Single node: executing <bound method ExperimentBuilder._generate_experiment_protocol.<locals>.DummyReporter.nothing of <yank.experiment.ExperimentBuilder._generate_experiment_protocol.<locals>.DummyReporter object at 0x2b634a0fb128>>
2017-08-28 18:27:39,547: Determining alchemical path for parameter lambda_electrostatics
Traceback (most recent call last):
  File "/home/elkhoury/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.17.0', 'console_scripts', 'yank')()
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 695, in run_experiments
    self._generate_experiments_protocols()
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 1798, in _generate_experiments_protocols
    group_nodes=1)
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/mpi.py", line 340, in distribute
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/mpi.py", line 340, in <listcomp>
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 1907, in _generate_experiment_protocol
    **kwargs)
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/pipeline.py", line 1575, in trailblaze_alchemical_protocol
    assert search_direction * (optimal_protocol[state_parameter][-1] - current_parameter_value) < 0
AssertionError
```
@andrrizzi moved to a bisection algorithm to rapidly find the next thermodynamic state with `sqrt(dU) ~ 0.5 kT`, but it sounds like the statistical errors in this scheme led this algorithm to fail. I think we may need to move to a probabilistic bisection search of the sort that @maxentile has used.

For `cyclo_harmonic_auto.e9584970`, it looks like something is wrong with our restraint algorithm. Can you provide the input files for that?
```
2017-08-30 16:17:28,850: Equilibration iteration 999/1000
2017-08-30 16:17:28,850: Propagating all replicas...
2017-08-30 16:17:28,850: Running _propagate_replica serially.
2017-08-30 16:17:29,519: Running _get_replica_move_statistics serially.
2017-08-30 16:17:29,519: Propagating all replicas took    0.670s
2017-08-30 16:17:29,520: Single node: executing <bound method ExperimentBuilder._generate_experiment_protocol.<locals>.DummyReporter.nothing of <yank.experiment.ExperimentBuilder._generate_experiment_protocol.<locals>.DummyReporter object at 0x2b211c9be358>>
Traceback (most recent call last):
  File "/home/elkhoury/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.17.0', 'console_scripts', 'yank')()
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 695, in run_experiments
    self._generate_experiments_protocols()
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 1798, in _generate_experiments_protocols
    group_nodes=1)
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/mpi.py", line 340, in distribute
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/mpi.py", line 340, in <listcomp>
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/yank/experiment.py", line 1902, in _generate_experiment_protocol
    sigma=3.0*unit.angstroms)
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/openmmtools/forcefactories.py", line 123, in restrain_atoms
    centroid = np.mean(sampler_state.positions[protein_atoms,:] / distance_unit, 0) * distance_unit
  File "/home/elkhoury/anaconda3/lib/python3.6/site-packages/simtk/unit/quantity.py", line 733, in __getitem__
    assert not is_quantity(self._value[key])
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by elkhoury** [comment]
For the **cyclo_harmonic_auto** case, we used the input files in the above **harmonic_auto.tar.gz** file (cyclodextrin_harmonic_auto.zip).

**Comment by maxentile** [comment]
> @andrrizzi moved to a bisection algorithm to rapidly find the next thermodynamic state with sqrt(dU) ~ 0.5 kT, but it sounds like the statistical errors in this scheme led this algorithm to fail. I think we may need to move to a probabilistic bisection search of the sort that @maxentile has used.

Hi, I'll take a closer look to confirm that this is the issue here. If so, it might be helpful to use this variant of bisection search for the case of noisy responses (described here https://people.orie.cornell.edu/pfrazier/pub/2013_WaeberFrazierHenderson.pdf).

An implementation of the algorithm is here: https://github.com/choderalab/integrator-benchmark/blob/master/benchmark/evaluation/thresholds.py#L66-L99 , and after discussing with @jchodera just now, we will probably move this into `openmmtools` soon, in case this is helpful in other contexts.

Later, a method along the lines of http://threeplusone.com/Rotskoff2017.pdf may be helpful for optimization of the full alchemical path, which would be more challenging than the current task of spacing of replicas along a pre-defined path but might yield higher efficiency.

**Comment by jchodera** [comment]
@maxentile: The relevant code is [here](https://github.com/choderalab/yank/blob/dfc99fb725c489be08e01cd785b1ff54b2395619/Yank/pipeline.py#L1474-L1601).

> Later, a method along the lines of http://threeplusone.com/Rotskoff2017.pdf may be helpful for optimization of the full alchemical path, which would be more challenging than the current task of spacing of replicas along a pre-defined path but might yield higher efficiency.

100% agree, but we have to punt that until after the YANK 1.0 paper.

**Comment by andrrizzi** [comment]
This issue should be fixed. Feel free to reopen if you stumble on to it again.
