### ISSUE TITLE
More user friendly error message for accidentally resuming without resume_setup: yes set

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#807]
Currently, we get the less than transparent error message
```
Traceback (most recent call last):
  File "/home/chodera/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/experiment.py", line 716, in run_experiments
    self._setup_experiments()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/experiment.py", line 1790, in _setup_experiments
    self._db.setup_all_systems()
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/pipeline.py", line 1044, in setup_all_systems
    group_nodes=1, sync_nodes=True)
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/mpi.py", line 388, in distribute
    results.append(task(distributed_arg, *other_args, **kwargs))
  File "/home/chodera/miniconda/lib/python3.5/site-packages/yank/pipeline.py", line 1124, in _setup_molecules
    os.makedirs(mol_dir)
  File "/home/chodera/miniconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'explicit/setup/molecules/STI_2'
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
which I think is going to confuse a bunch of users. Can we instead add a check that says something useful like
```
Existing setup files exist, but `resume_setup: yes` not set.
Either clear out the existing setup files or set `resume_setup: yes` to proceed.
```
Also, why not make `resume_setup: yes` the default? I can't think of a good reason not to.

**Comment by andrrizzi** [comment]
Hmm. This is a Python exception, not the message that we raise when we resume with `resume_setup: no`.

It looks like a concurrency problem (i.e., multiple processes check that the directory exists and then try to create it). Since we dropped Python 2, we can now make use of the argument `os.makedirs(..., exist_ok=True)` everywhere, although it is unclear to me how we would end up in this situation.

The first thing that comes to mind is that all your MPI processes may have been assigned somehow to the same rank.

I'm fine setting the default of `resume_setup` to `true`.
