### ISSUE TITLE
CL_OUT_OF_RESOURCES error 

### ISSUE THREAD

**Issue by spadavec** [choderalab/yank#832]
I have a feeling this is a nebulous error thats NVIDIAs fault for not allocating enough memory to a process, but I got the following error on a explicit calculation: 

```
2017-11-20 23:21:38,690: Accepted 1681582/14623232 attempted swaps (11.5%)
2017-11-20 23:21:38,690: Propagating all replicas...
2017-11-20 23:21:38,690: Running _propagate_replica serially.
2017-11-20 23:22:04,471: WARNING - openmmtools.mcmc - Potential energy is NaN after 0 attempts of integration with move LangevinDynamicsMove Attempting a restart...
OpenCL internal error: CL_OUT_OF_RESOURCES error executing CL_COMMAND_READ_BUFFER on GeForce GTX 1080 Ti (Device 0).

Traceback (most recent call last):
  File "/home/spadavec/miniconda2/bin/yank", line 11, in <module>
    load_entry_point('yank==0.17.0', 'console_scripts', 'yank')()
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/experiment.py", line 708, in run_experiments
    completed[exp_index] = self._run_experiment(exp)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/experiment.py", line 2281, in _run_experiment
    built_experiment.run(n_iterations=switch_experiment_interval)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/experiment.py", line 403, in run
    alchemical_phase.run(n_iterations=iterations_to_run)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/yank.py", line 784, in run
    self._sampler.run(n_iterations=n_iterations)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/repex.py", line 1848, in run
    self._propagate_replicas()
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/openmmtools/utils.py", line 85, in _wrapper
    return func(*args, **kwargs)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/repex.py", line 2070, in _propagate_replicas
    send_results_to=0)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/mpi.py", line 340, in distribute
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/yank/repex.py", line 2098, in _propagate_replica
    mcmc_move.apply(thermodynamic_state, sampler_state)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/openmmtools/mcmc.py", line 371, in apply
    move.apply(thermodynamic_state, sampler_state)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/openmmtools/mcmc.py", line 1103, in apply
    super(LangevinDynamicsMove, self).apply(thermodynamic_state, sampler_state)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/openmmtools/mcmc.py", line 666, in apply
    sampler_state.apply_to_context(context, ignore_velocities=self.reassign_velocities)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/openmmtools/states.py", line 1717, in apply_to_context
    context.setPositions(self._positions)
  File "/home/spadavec/miniconda2/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 11658, in setPositions
    return _openmm.Context_setPositions(self, positions)
Exception: Error downloading array posq: clEnqueueReadBuffer (-5)
2017-11-20 23:22:04,707: Single node: executing <bound method Reporter.close of <yank.repex.Reporter object at 0x7f89da9ce590>>
```

It looks like this error (or something similar) has been seen before: 

https://github.com/pandegroup/openmm/issues/926

But I'm using wildly different package versions: 

```
yank .   0.17
openmm .   7.2
openmmtools .   0.8.1
cuda .   9.0 
nvidia-driver .   384.98
```

Should I drop by ```CUDA``` version down to 8.x or 7.x and have a different openmm/openmmtools combo? I have another cluster that dropped out in a similar fashion (I remember seeing the same error, but the machine got rebooted so can't say for sure), and it has the following: 

```
yank .   0.17
openmm .   7.1.1
openmmtools .   0.7.5
cuda .   8.0
nvidia-driver .   384.9
```
Apologies for all the conflating factors--I can swap versions around as you see fit! 

EDIT: I should note that this GPU had 2 jobs running on it initially--just one dropped out after ~20 iterations, and the other is still running.

**Comment by jchodera** [comment]
I suspect that this is an issue with running into a `NaN` and not being able to fully reinitialize the context to recover at that point. 

We've just released an updated version of YANK ([0.19.0](https://github.com/choderalab/yank/releases/tag/0.19.0)) that may improve stability, but @andrrizzi is working with @Lnaden to implement a more robust way to reinitialize the `Context` after encountering a NaN. I'm surprised this happened on OpenCL, however---I think we've only seen these issues recently on CUDA.

**Comment by spadavec** [comment]
OK, I'll bump up `yank` to 0.19 and see if that helps--just to clarify, this is all running using CUDA, so not entirely sure why its throwing an OpenCL error?

**Comment by jchodera** [comment]
That's odd. Did you set your GPU to shared mode? I imagine you must have since you had two jobs running on it.

**Comment by Lnaden** [comment]
That is very odd that its throwing OpenCL errors, there are unique CUDA/OpenCL-based errors for the nvidia drivers throw, so the fact that its using OpenCL seems odd. Are you using the default `platform` in the YAML file, or specifically setting it to `CUDA`?

**Comment by spadavec** [comment]
@jchodera Yes, it was in shared mode. I'm updating to `yank 0.19` to see if that changes anything now

@Lnaden In one case, it was just default `platform` (which goes to CUDA), and in the other case, I explicitly set it to `CUDA` in the yaml.
