### ISSUE TITLE
Encase parts of setup pipeline in try...except blocks

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#895]
This may be related to filesystem issues, but on ORNL TITAN (using scratch storage), I am running into failures like
```
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/16840756/yank", line 11, in <module>
    load_entry_point('yank==0.20.1', 'console_scripts', 'yank')()
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/commands/script.py", line 123, in dispatch
    yaml_builder.run_experiments()
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 797, in run_experiments
    self._setup_experiments()
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/experiment.py", line 2347, in _setup_experiments
    self._db.setup_all_systems()
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/pipeline.py", line 1285, in setup_all_systems
    send_results_to=None, group_size=1, sync_nodes=True)
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/mpi.py", line 479, in distribute
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/mpi.py", line 479, in <listcomp>
    all_results = [task(job_args, *other_args, **kwargs) for job_args in distributed_args]
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/pipeline.py", line 1459, in _setup_molecules
    apply_pdbfixer(mol_descr['filepath'], output_file_path, mol_descr['pdbfixer'])
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/yank/pipeline.py", line 832, in apply_pdbfixer
    fixer = PDBFixer(input_file_path)
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/pdbfixer/pdbfixer.py", line 238, in __init__
    self._initializeFromPDB(file)
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/pdbfixer/pdbfixer.py", line 275, in _initializeFromPDB
    structure = PdbStructure(file)
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 152, in __init__
    self._load(input_stream)
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 163, in _load
    self._add_atom(Atom(pdb_line, self, self.extraParticleIdentifier))
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 781, in __init__
    y = float(pdb_line[38:46])
ValueError: could not convert string to float: '     O  '
```
In general, it seems like it might be good for us to encase things that might fail, such as this `PDBFixer()` call, in `try...except` blocks so that they don't take out a huge experiment if one item fails to be set up properly.

**Comment by andrrizzi** [comment]
Closing this in favor of #960, which is more general.
