### ISSUE TITLE
AssertionError when trying the tutorial example "p-xylene binding to T4 lysozyme L99A in explicit solvent"

### ISSUE THREAD

**Issue by YingChihChiang** [choderalab/yank#922]
Hi everyone,

  After learned that one can use YANK to set up free energy calculations in OpenMM, I am excited to try out this cool package, starting with the YANK tutorials.  When I try to run the examples of "p-xylene binding to T4 lysozyme L99A in explicit solvent" using the scripts provided via conda, the job dies with the following error message:

(... deleted)
2018-03-23 14:16:17,638: Create alchemically modified system took    1.258s
Traceback (most recent call last):
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/experiment.py", line 730, in run_experiments
    completed[exp_index] = self._run_experiment(exp)
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/experiment.py", line 2325, in _run_experiment
    built_experiment.run(n_iterations=switch_experiment_interval)
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/experiment.py", line 400, in run
    alchemical_phase = phase.initialize_alchemical_phase()
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/experiment.py", line 279, in initialize_alchemical_phase
    alchemical_phase = self.create_alchemical_phase()
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/experiment.py", line 265, in create_alchemical_phase
    **create_kwargs)
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/yank/yank.py", line 608, in create
    thermodynamic_state=thermodynamic_state, composable_states=composable_states)
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/openmmtools/states.py", line 2280, in __init__
    self._initialize(thermodynamic_state, composable_states)
  File "/home/ycc1m18/Soft/miniconda/envs/OpenMM/lib/python3.6/site-packages/openmmtools/states.py", line 2459, in _initialize
    assert isinstance(composable_state, IComposableState)
AssertionError

From the output directory, I can see the systems are constructed properly via LEaP.  Also, I can run the hydration examples without any problem.  Does anyone know the reason for this error,e.g. missing packages or incorrect environment setting, please?  My OpenMM and YANK installation are all done through conda, but it is still likely that something is missing. Sorry for posting the question here, but the SimTk YANK forum seems to be less visited.  Many thanks for your help!

**Comment by YingChihChiang** [comment]
After seeing the package dependency in setup.py, I realize that the cerberus and pdbfixer are missing.  Reinstalling yank with these two packages solved the problem.  Sorry for the trouble!

**Comment by andrrizzi** [comment]
Glad you managed to fix the problem!
