### ISSUE TITLE
`yank analyze report` broken on osx when Harmonic/FlatBottom used

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#941]
The latest release has an issue when `yank analyze report` is used with `Harmonic` on `osx`:
```
lski2414:cucurbit7uril choderaj$ yank analyze report --store repex/experiments/a1-experiment --output repex.ipynb 
Rendering notebook as a .ipynb file...
Processing notebook now, this may take a while...
2018-04-01 12:03:43,404: Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.21.2', 'console_scripts', 'yank')()
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/commands/analyze.py", line 97, in dispatch
    return dispatch_report(args)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/commands/analyze.py", line 240, in dispatch_report
    processed_notebook, resources = ep.preprocess(loaded_notebook, resource_data)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 262, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 286, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
report.generate_free_energy()
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in __get__(self, instance, owner_class)
    403         try:
--> 404             value = instance._cache[self.name]
    405         except KeyError:

KeyError: 'mbar'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in __get__(self, instance, owner_class)
    403         try:
--> 404             value = instance._cache[self.name]
    405         except KeyError:

KeyError: 'unbiased_decorrelated_u_ln'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-9-dc5b0787a332> in <module>()
----> 1 report.generate_free_energy()

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/reports/notebook.py in generate_free_energy(self)
    571         for phase_name in self.phase_names:
    572             analyzer = self.analyzers[phase_name]
--> 573             data[phase_name] = analyzer.analyze_phase()
    574             kT = analyzer.kT
    575 

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/analyze.py in analyze_phase(self, cutoff)
    111         data = {}
    112         # Accumulate free energy differences
--> 113         Deltaf_ij, dDeltaf_ij = self.get_free_energy()
    114         DeltaH_ij, dDeltaH_ij = self.get_enthalpy()
    115         data['DeltaF'] = Deltaf_ij[self.reference_states[0], self.reference_states[1]]

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in get_free_energy(self)
   1768         """
   1769         if self._computed_observables['free_energy'] is None:
-> 1770             self._compute_free_energy()
   1771         free_energy_dict = self._computed_observables['free_energy']
   1772         return free_energy_dict['value'], free_energy_dict['error']

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in _compute_free_energy(self)
   1721         Estimate free energies of all alchemical states.
   1722         """
-> 1723         nstates = self.mbar.N_k.size
   1724 
   1725         # Get matrix of dimensionless free energy differences and uncertainty estimate.

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in __get__(self, instance, owner_class)
    404             value = instance._cache[self.name]
    405         except KeyError:
--> 406             value = self._get_default(instance)
    407             # Cache default value for next use.
    408             instance._update_cache(self.name, value, self._check_changes)

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in _get_default(self, instance)
    425             raise AttributeError(err_msg)
    426         elif callable(self._default):
--> 427             value = self._default(self, instance)
    428         else:
    429             value = self._default

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in mbar(self, instance)
   1937     @mbar.default
   1938     def mbar(self, instance):
-> 1939         return instance._create_mbar(instance._unbiased_decorrelated_u_ln,
   1940                                      instance._unbiased_decorrelated_N_l)
   1941 

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in __get__(self, instance, owner_class)
    404             value = instance._cache[self.name]
    405         except KeyError:
--> 406             value = self._get_default(instance)
    407             # Cache default value for next use.
    408             instance._update_cache(self.name, value, self._check_changes)

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in _get_default(self, instance)
    425             raise AttributeError(err_msg)
    426         elif callable(self._default):
--> 427             value = self._default(self, instance)
    428         else:
    429             value = self._default

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in _unbiased_decorrelated_u_ln(self, instance)
   1918     @_unbiased_decorrelated_u_ln.default
   1919     def _unbiased_decorrelated_u_ln(self, instance):
-> 1920         return instance._compute_mbar_unbiased_energies()[0]
   1921 
   1922     _unbiased_decorrelated_N_l = CachedProperty(

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in _compute_mbar_unbiased_energies(self)
   1417         # Compute restraint energies/distances.
   1418         energies_ln, distances_ln = self._compute_restraint_energies(restraint_force, weights_group1,
-> 1419                                                                      weights_group2)
   1420 
   1421         # Convert energies to kT unit for comparison to energy cutoff.

~/miniconda/lib/python3.6/site-packages/yank-0.21.2-py3.6-macosx-10.9-x86_64.egg/yank/multistate/multistateanalyzer.py in _compute_restraint_energies(self, restraint_force, weights_group1, weights_group2)
   1568         # Create context used to compute the energies.
   1569         integrator = openmm.VerletIntegrator(1.0*units.femtosecond)
-> 1570         context = openmm.Context(reduced_system, integrator)
   1571 
   1572         # TODO: we need to provide a reporter generator to iterate over single

~/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py in __init__(self, *args)
   6263             a set of values for platform-specific properties. Keys are the property names.
   6264         """
-> 6265         this = _openmm.new_Context(*args)
   6266         try:
   6267             self.this.append(this)

Exception: CustomCentroidBondForce requires a device that supports 64 bit atomic operations
Exception: CustomCentroidBondForce requires a device that supports 64 bit atomic operations
```
The `--skipunbiasing` flag appears to have no effect here.

**Comment by andrrizzi** [comment]
> Exception: CustomCentroidBondForce requires a device that supports 64 bit atomic operations

OpenMM can't create `CustomCentroidBondForce`s on 32-bit platforms, and many MacBooks default to a 32-bit OpenCL platform. I'm thinking we can fix the platform to be `CPU` to circumvent this. It may be even faster than using the GPU considering we only need to compute the centroid bond force energy.

**Comment by jchodera** [comment]
Sounds like a good workaround! Do we force the platform currently? If not, I'm confused why Context doesn't fall back to the first Platform that includes support for all kernels.

**Comment by andrrizzi** [comment]
> Do we force the platform currently?

Nope.

> If not, I'm confused why Context doesn't fall back to the first Platform that includes support for all kernels.

Good question. Probably worth to open an issue on the OpenMM's tracker.
