### ISSUE TITLE
Issue running ABFE on serialized openmm system in Yank 0.20.0

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#948]
Hi There, I’m trying to run ABFE calculation on Toluene bonded to Lysozyme (it is just a test system). Unfortunately, I’m having some issues. I’m inputting Yank by using .xml files produced by serializing my openmm systems: the solvated complex and solvated ligand. I’m using Yank 0.20.0 and openmmtools 0.14.0 (I have attached a list of the conda packages installed in my environment). I’m getting the following error running Yank with the command: yank script - -yaml=explicit.yaml

```
Traceback (most recent call last):
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/bin/yank", line 11, in <module>
    load_entry_point('yank==0.20.0', 'console_scripts', 'yank')()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/commands/script.py", line 113, in dispatch
    yaml_builder.run_experiments()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/experiment.py", line 808, in run_experiments
    completed[exp_index] = self._run_experiment(exp)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/experiment.py", line 2874, in _run_experiment
    built_experiment.run(n_iterations=switch_experiment_interval)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/experiment.py", line 471, in run
    alchemical_phase = phase.initialize_alchemical_phase()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/experiment.py", line 339, in initialize_alchemical_phase
    alchemical_phase = self.create_alchemical_phase()
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/experiment.py", line 325, in create_alchemical_phase
    **create_kwargs)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/yank/yank.py", line 1024, in create
    thermodynamic_state=thermodynamic_state, composable_states=composable_states)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/openmmtools/states.py", line 2280, in __init__
    self._initialize(thermodynamic_state, composable_states)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record_last/lib/python3.5/site-packages/openmmtools/states.py", line 2459, in _initialize
    assert isinstance(composable_state, IComposableState)
AssertionError
```
I'm also getting some warning from Yank generated from openmmtools.alchemy complaining that some particles have Lennard-Jones sigma = 0 but resetting the value to a default (setting sigma=1A). I'm not sure if this can be the problem.

In the attached file you will find all the Yank required files and the produced Yank output directory. I would appreciate if someone could help me with that explaining what I'm doing wrong. 

Thanks a lot, Gaetano

[TEST.zip](https://github.com/choderalab/yank/files/1899823/TEST.zip)

**Comment by andrrizzi** [comment]
Hi @nividic . Can you try bumping YANK to 0.20.1? There was a change with `openmmtools 0.14.0`, and I made YANK compatible with that openmmtools version in that bugfix release.

**Comment by nividic** [comment]
@andrrizzi Thanks this has fixed my issue! I would like to use the latest Yank version (0.21.1) but I'm having some issue there as well on the same system. After updating my conda environment (Yank=0.21.1 and openmmtools=0.15.0) and my .yaml file to support your latest yaml syntax I'm getting another error:
```
Traceback (most recent call last):
  File "/Users/gcalabro/local/miniconda3/envs/test_gac/bin/yank", line 11, in <module>
    load_entry_point('yank==0.21.1', 'console_scripts', 'yank')()
  File "/Users/gcalabro/local/miniconda3/envs/test_gac/lib/python3.5/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/gcalabro/local/miniconda3/envs/test_gac/lib/python3.5/site-packages/yank/commands/script.py", line 136, in dispatch
    yaml_builder.run_experiments()
  File "/Users/gcalabro/local/miniconda3/envs/test_gac/lib/python3.5/site-packages/yank/experiment.py", line 788, in run_experiments
    completed[exp_index] = self._run_experiment(exp)
  File "/Users/gcalabro/local/miniconda3/envs/test_gac/lib/python3.5/site-packages/yank/experiment.py", line 3062, in _run_experiment
    built_experiment = self._build_experiment(experiment_path, experiment)
  File "/Users/gcalabro/local/miniconda3/envs/test_gac/lib/python3.5/site-packages/yank/experiment.py", line 2970, in _build_experiment
    gromacs_include_dir=gromacs_include_dir)
  File "/Users/gcalabro/local/miniconda3/envs/test_gac/lib/python3.5/site-packages/yank/pipeline.py", line 495, in read_system_files
    sampler_state = mmtools.states.SamplerState(positions=positions, box_vectors=box_vectors)
UnboundLocalError: local variable 'box_vectors' referenced before assignment
```
Would you like me to open another issue case for this?

Thank you so much,

Gaetano

**Comment by andrrizzi** [comment]
Ah! You found a bug that we introduced with the new release. Thank you for catching it. I'll create a fix today.

**Comment by nividic** [comment]
Ok Thanks, I'm closing this issue
