### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#951]
See https://travis-ci.org/choderalab/yank/jobs/367661862#L1162-L1183
```
Leaving build/test directories:
  Work:	 /home/travis/miniconda/conda-bld/work 
  Test:	 /home/travis/miniconda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:	source activate  /home/travis/miniconda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl 
  Build:	source activate  /home/travis/miniconda/conda-bld/_build_env 
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 2105, in build_tree
    notest=notest,
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1294, in build
    raise e
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: set(["openmm[version='>=7.3.0']"])
```
I'm not sure why this is failing since there are `dev` versions of 7.3.2 available here:
https://anaconda.org/omnia/openmm/files

**Comment by Lnaden** [comment]
That is expected to be failing. Each travis build runs 3 tests, 2 on Python 3.5 and 3.6 without the `dev` channel, and 1 `dev` channel build which is allowed to fail. Since we don't want to release YANK versions which depend on the `dev` versions of OpenMM, we want those to fail for that reason, but still allow testing of things in `dev` so we can do a bit of future planning

**Comment by jchodera** [comment]
The Travis builds are still being marked as failed. Is this a problem elsewhere?

**Comment by Lnaden** [comment]
We expect the builds to fail though, so the non-dev versions of the WIP RMSD restraint code should fail, the dev builds of them should not though (see #950 and #952 for fixes to that though)

**Comment by Lnaden** [comment]
RMSD restraint is in and the dev and non-dev versions play nicely with each other
